/* CrunchyMurmur renderer localisation. Keep catalogs structurally identical. */
(() => {
  const supported = ['en', 'it', 'es', 'pt', 'fr', 'de', 'da', 'no', 'sv', 'zh', 'ko', 'ja'];
  const phrases = {
    'CLI default (recommended)': ['Predefinito della CLI (consigliato)','Predeterminado de la CLI (recomendado)','Predefinição da CLI (recomendado)','Valeur par défaut de la CLI (recommandée)','CLI-Standard (empfohlen)','CLI-standard (anbefalet)','CLI-standard (anbefalt)','CLI-standard (rekommenderas)','CLI 默认值（推荐）','CLI 기본값(권장)','CLI のデフォルト（推奨）'],
    'Maximum — highest reasoning depth': ['Massimo — massima profondità di ragionamento','Máximo — máxima profundidad de razonamiento','Máximo — maior profundidade de raciocínio','Maximum — profondeur de raisonnement maximale','Maximum — höchste Denktiefe','Maksimum — højeste ræsonneringsdybde','Maksimum — høyeste resonneringsdybde','Maximum — högsta resonemangsdjup','最大 — 最高推理深度','최대 — 가장 높은 추론 깊이','最大 — 最高の推論深度'],
    'Ultra — maximum reasoning with delegation': ['Ultra — ragionamento massimo con delega','Ultra — razonamiento máximo con delegación','Ultra — raciocínio máximo com delegação','Ultra — raisonnement maximal avec délégation','Ultra — maximales Denken mit Delegierung','Ultra — maksimal ræsonnering med delegering','Ultra — maksimal resonnering med delegering','Ultra — maximalt resonemang med delegering','超强 — 最高推理并自动委派','울트라 — 위임을 포함한 최대 추론','ウルトラ — 委任を伴う最大推論'],
    'Effective configuration: {0}': ['Configurazione effettiva: {0}','Configuración efectiva: {0}','Configuração efetiva: {0}','Configuration effective : {0}','Wirksame Konfiguration: {0}','Aktiv konfiguration: {0}','Gjeldende konfigurasjon: {0}','Aktiv konfiguration: {0}','生效配置：{0}','적용 구성: {0}','有効な構成: {0}'],
    'Effort': ['Impegno','Esfuerzo','Esforço','Effort','Aufwand','Indsats','Innsats','Ansträngning','投入程度','작업 강도','処理強度'],
    'Extra high — slowest, highest subscription usage': ['Molto alto — più lento, massimo utilizzo dell’abbonamento','Muy alto — el más lento y con mayor uso de la suscripción','Muito alto — mais lento e com maior utilização da subscrição','Très élevé — le plus lent et l’utilisation d’abonnement la plus élevée','Sehr hoch — am langsamsten, höchste Abonnementnutzung','Ekstra høj — langsomst, højeste abonnementsforbrug','Ekstra høy — tregest, høyest abonnementsbruk','Extra hög — långsammast, högst abonnemangsanvändning','超高 — 最慢，订阅用量最高','매우 높음 — 가장 느리고 구독 사용량이 가장 높음','最高 — 最も遅く、サブスクリプション使用量が最大'],
    'High — better for complex transcripts': ['Alto — migliore per trascrizioni complesse','Alto — mejor para transcripciones complejas','Alto — melhor para transcrições complexas','Élevé — mieux adapté aux transcriptions complexes','Hoch — besser für komplexe Transkripte','Høj — bedre til komplekse transskriptioner','Høy — bedre for komplekse transkripsjoner','Hög — bättre för komplexa transkriptioner','高 — 更适合复杂转录','높음 — 복잡한 전사에 적합','高 — 複雑な文字起こしに適する'],
    'Low — fastest, lowest subscription usage': ['Basso — più veloce, minimo utilizzo dell’abbonamento','Bajo — el más rápido y con menor uso de la suscripción','Baixo — mais rápido e com menor utilização da subscrição','Faible — le plus rapide et l’utilisation d’abonnement la plus faible','Niedrig — am schnellsten, geringste Abonnementnutzung','Lav — hurtigst, laveste abonnementsforbrug','Lav — raskest, lavest abonnementsbruk','Låg — snabbast, lägst abonnemangsanvändning','低 — 最快，订阅用量最低','낮음 — 가장 빠르고 구독 사용량이 가장 적음','低 — 最速でサブスクリプション使用量が最小'],
    'Medium — recommended for summaries': ['Medio — consigliato per i riepiloghi','Medio — recomendado para resúmenes','Médio — recomendado para resumos','Moyen — recommandé pour les résumés','Mittel — für Zusammenfassungen empfohlen','Mellem — anbefales til resuméer','Middels — anbefalt for sammendrag','Medel — rekommenderas för sammanfattningar','中 — 建议用于摘要','중간 — 요약에 권장','中 — 要約に推奨'],
    'Reasoning effort': ['Impegno di ragionamento','Esfuerzo de razonamiento','Esforço de raciocínio','Effort de raisonnement','Denkaufwand','Ræsonneringsindsats','Resonneringsinnsats','Resonemangsnivå','推理强度','추론 강도','推論強度'],
    'Anthropic fallback sends transcript text, but not audio, to Anthropic. It requires an Anthropic account and API key. Provider charges may apply.': ['Il fallback Anthropic invia ad Anthropic il testo della trascrizione, ma non l’audio. Richiede un account Anthropic e una chiave API. Potrebbero essere applicati costi.','La alternativa de Anthropic envía a Anthropic el texto de la transcripción, pero no el audio. Requiere una cuenta de Anthropic y una clave de API. Puede haber cargos.','A alternativa Anthropic envia o texto da transcrição, mas não o áudio, para a Anthropic. Requer uma conta Anthropic e uma chave de API. Poderão aplicar-se custos.','Le recours à Anthropic envoie le texte de la transcription, mais pas l’audio, à Anthropic. Il nécessite un compte Anthropic et une clé API. Des frais peuvent s’appliquer.','Die Anthropic-Ausweichoption sendet den Transkripttext, nicht jedoch das Audio, an Anthropic. Ein Anthropic-Konto und ein API-Schlüssel sind erforderlich. Kosten können anfallen.','Anthropic-reserveløsningen sender transskriptionsteksten, men ikke lyden, til Anthropic. Det kræver en Anthropic-konto og API-nøgle. Der kan forekomme udgifter.','Anthropic-reserveløsningen sender transkripsjonsteksten, men ikke lyden, til Anthropic. Det krever en Anthropic-konto og API-nøkkel. Kostnader kan påløpe.','Anthropic-alternativet skickar transkriptionstexten, men inte ljudet, till Anthropic. Ett Anthropic-konto och en API-nyckel krävs. Kostnader kan tillkomma.','Anthropic 回退会将转录文本（不含音频）发送给 Anthropic。需要 Anthropic 帐户和 API 密钥。可能产生费用。','Anthropic 대체 처리는 오디오를 제외한 전사 텍스트를 Anthropic에 보냅니다. Anthropic 계정과 API 키가 필요하며 요금이 부과될 수 있습니다.','Anthropic フォールバックでは、音声ではなく文字起こしテキストを Anthropic に送信します。Anthropic アカウントと API キーが必要です。料金が発生する場合があります。'],
    'AI formatting removes filler words and false starts, fixes punctuation and capitalization, and turns spoken lists into bullets. It does not change the intended meaning.': ['La formattazione AI rimuove intercalari e false partenze, corregge punteggiatura e maiuscole e trasforma gli elenchi dettati in punti elenco. Non cambia il significato voluto.','El formato con IA elimina muletillas y falsos comienzos, corrige la puntuación y las mayúsculas y convierte las listas habladas en viñetas. No cambia el significado pretendido.','A formatação por IA remove palavras de preenchimento e falsos começos, corrige a pontuação e as maiúsculas e transforma listas faladas em marcadores. Não altera o significado pretendido.','La mise en forme par IA supprime les mots de remplissage et les faux départs, corrige la ponctuation et les majuscules, et transforme les listes dictées en puces. Elle ne modifie pas le sens voulu.','Die KI-Formatierung entfernt Füllwörter und Fehlansätze, korrigiert Zeichensetzung und Großschreibung und wandelt gesprochene Listen in Aufzählungen um. Die beabsichtigte Bedeutung bleibt unverändert.','AI-formatering fjerner fyldord og fejlstarter, retter tegnsætning og store bogstaver og omdanner talte lister til punktlister. Den ændrer ikke den tilsigtede betydning.','KI-formatering fjerner fyllord og feilstarter, retter tegnsetting og store bokstaver og gjør talte lister om til punktlister. Den endrer ikke den tiltenkte betydningen.','AI-formatering tar bort utfyllnadsord och omstarter, rättar interpunktion och versaler och omvandlar talade listor till punktlistor. Den ändrar inte den avsedda betydelsen.','AI 格式化会删除填充词和重新开始的片段，修正标点和大小写，并将口述列表转为项目符号。它不会改变原意。','AI 형식 지정은 추임새와 잘못 시작한 부분을 제거하고 문장 부호와 대소문자를 바로잡으며 구술 목록을 글머리표로 변환합니다. 의도한 의미는 바꾸지 않습니다.','AI フォーマットは、フィラーや言い直しを削除し、句読点と大文字・小文字を修正し、口頭のリストを箇条書きに変換します。意図した意味は変更しません。'],
    'Cloud processing sends transcript text, but not audio, to Groq. It requires a Groq account and API key; no model download or local storage is needed. Provider charges may apply.': ['L’elaborazione nel cloud invia a Groq il testo della trascrizione, ma non l’audio. Richiede un account Groq e una chiave API; non servono download di modelli né spazio locale. Potrebbero essere applicati costi.','El procesamiento en la nube envía a Groq el texto de la transcripción, pero no el audio. Requiere una cuenta de Groq y una clave de API; no hace falta descargar modelos ni usar almacenamiento local. Puede haber cargos.','O processamento na nuvem envia o texto da transcrição, mas não o áudio, para a Groq. Requer uma conta Groq e uma chave de API; não é necessário transferir modelos nem usar armazenamento local. Poderão aplicar-se custos.','Le traitement dans le cloud envoie le texte de la transcription, mais pas l’audio, à Groq. Il nécessite un compte Groq et une clé API ; aucun téléchargement de modèle ni stockage local n’est requis. Des frais peuvent s’appliquer.','Bei der Cloud-Verarbeitung wird der Transkripttext, nicht jedoch das Audio, an Groq gesendet. Ein Groq-Konto und ein API-Schlüssel sind erforderlich; Modelldownload und lokaler Speicher sind nicht nötig. Kosten können anfallen.','Cloudbehandling sender transskriptionsteksten, men ikke lyden, til Groq. Det kræver en Groq-konto og API-nøgle; der kræves ingen modeldownload eller lokal lagerplads. Der kan forekomme udgifter.','Skybehandling sender transkripsjonsteksten, men ikke lyden, til Groq. Det krever en Groq-konto og API-nøkkel; ingen modellnedlasting eller lokal lagring er nødvendig. Kostnader kan påløpe.','Molnbearbetning skickar transkriptionstexten, men inte ljudet, till Groq. Ett Groq-konto och en API-nyckel krävs; ingen modellhämtning eller lokal lagring behövs. Kostnader kan tillkomma.','云处理会将转录文本（不含音频）发送给 Groq。需要 Groq 帐户和 API 密钥；无需下载模型或使用本地存储。可能产生费用。','클라우드 처리는 오디오를 제외한 전사 텍스트를 Groq에 보냅니다. Groq 계정과 API 키가 필요하며 모델 다운로드나 로컬 저장 공간은 필요하지 않습니다. 요금이 부과될 수 있습니다.','クラウド処理では、音声ではなく文字起こしテキストを Groq に送信します。Groq アカウントと API キーが必要ですが、モデルのダウンロードやローカルストレージは不要です。料金が発生する場合があります。'],
    'Formatting errors always fall back to the raw transcript so dictation is not lost.': ['In caso di errore viene sempre usata la trascrizione grezza, così la dettatura non va persa.','Si se produce un error, siempre se usa la transcripción sin procesar para no perder el dictado.','Em caso de erro, é sempre usada a transcrição sem processamento para que o ditado não se perca.','En cas d’erreur, la transcription brute est toujours utilisée afin de ne pas perdre la dictée.','Bei Fehlern wird immer das Rohtranskript verwendet, damit das Diktat nicht verloren geht.','Ved fejl bruges den rå transskription altid, så dikteringen ikke går tabt.','Ved feil brukes alltid den rå transkripsjonen, slik at dikteringen ikke går tapt.','Vid fel används alltid den råa transkriptionen så att dikteringen inte går förlorad.','如果格式化失败，将始终使用原始转录，以免丢失听写内容。','오류가 발생하면 받아쓰기 내용이 손실되지 않도록 항상 원본 전사로 돌아갑니다.','エラー時は必ず生の文字起こしに戻り、音声入力が失われないようにします。'],
    'When Groq is unavailable': ['Quando Groq non è disponibile','Cuando Groq no está disponible','Quando a Groq não está disponível','Lorsque Groq est indisponible','Wenn Groq nicht verfügbar ist','Når Groq ikke er tilgængelig','Når Groq ikke er tilgjengelig','När Groq inte är tillgängligt','Groq 不可用时','Groq을 사용할 수 없을 때','Groq が利用できない場合'],
    'Paste the raw transcript (no other provider)': ['Incolla la trascrizione grezza (nessun altro provider)','Pegar la transcripción sin procesar (sin otro proveedor)','Colar a transcrição sem processamento (sem outro fornecedor)','Coller la transcription brute (aucun autre fournisseur)','Rohtranskript einfügen (kein anderer Anbieter)','Indsæt den rå transskription (ingen anden udbyder)','Lim inn rå transkripsjon (ingen annen leverandør)','Klistra in den råa transkriptionen (ingen annan leverantör)','粘贴原始转录（不使用其他提供商）','원본 전사 붙여넣기(다른 공급자 사용 안 함)','生の文字起こしを貼り付ける（他のプロバイダーは使用しない）'],
    'Use Anthropic Claude Haiku if its API key is configured': ['Usa Anthropic Claude Haiku se la chiave API è configurata','Usar Anthropic Claude Haiku si su clave de API está configurada','Usar o Anthropic Claude Haiku se a chave de API estiver configurada','Utiliser Anthropic Claude Haiku si sa clé API est configurée','Anthropic Claude Haiku verwenden, wenn der API-Schlüssel konfiguriert ist','Brug Anthropic Claude Haiku, hvis API-nøglen er konfigureret','Bruk Anthropic Claude Haiku hvis API-nøkkelen er konfigurert','Använd Anthropic Claude Haiku om API-nyckeln är konfigurerad','如果已配置 API 密钥，则使用 Anthropic Claude Haiku','API 키가 설정되어 있으면 Anthropic Claude Haiku 사용','API キーが設定済みの場合は Anthropic Claude Haiku を使用'],
    'Llama 3.1 8B — Cloud, Groq (fastest)': ['Llama 3.1 8B — Cloud, Groq (più veloce)','Llama 3.1 8B — Nube, Groq (más rápido)','Llama 3.1 8B — Nuvem, Groq (mais rápido)','Llama 3.1 8B — Cloud, Groq (le plus rapide)','Llama 3.1 8B — Cloud, Groq (am schnellsten)','Llama 3.1 8B — Cloud, Groq (hurtigst)','Llama 3.1 8B — Sky, Groq (raskest)','Llama 3.1 8B — Moln, Groq (snabbast)','Llama 3.1 8B — 云端，Groq（最快）','Llama 3.1 8B — 클라우드, Groq(가장 빠름)','Llama 3.1 8B — クラウド、Groq（最速）'],
    'Llama 3.3 70B — Cloud, Groq (better quality)': ['Llama 3.3 70B — Cloud, Groq (qualità migliore)','Llama 3.3 70B — Nube, Groq (mejor calidad)','Llama 3.3 70B — Nuvem, Groq (melhor qualidade)','Llama 3.3 70B — Cloud, Groq (meilleure qualité)','Llama 3.3 70B — Cloud, Groq (bessere Qualität)','Llama 3.3 70B — Cloud, Groq (bedre kvalitet)','Llama 3.3 70B — Sky, Groq (bedre kvalitet)','Llama 3.3 70B — Moln, Groq (bättre kvalitet)','Llama 3.3 70B — 云端，Groq（质量更好）','Llama 3.3 70B — 클라우드, Groq(더 나은 품질)','Llama 3.3 70B — クラウド、Groq（高品質）'],
    'Llama 4 Scout 17B — Cloud, Groq': ['Llama 4 Scout 17B — Cloud, Groq','Llama 4 Scout 17B — Nube, Groq','Llama 4 Scout 17B — Nuvem, Groq','Llama 4 Scout 17B — Cloud, Groq','Llama 4 Scout 17B — Cloud, Groq','Llama 4 Scout 17B — Cloud, Groq','Llama 4 Scout 17B — Sky, Groq','Llama 4 Scout 17B — Moln, Groq','Llama 4 Scout 17B — 云端，Groq','Llama 4 Scout 17B — 클라우드, Groq','Llama 4 Scout 17B — クラウド、Groq'],
    'Qwen 3 32B — Cloud, Groq': ['Qwen 3 32B — Cloud, Groq','Qwen 3 32B — Nube, Groq','Qwen 3 32B — Nuvem, Groq','Qwen 3 32B — Cloud, Groq','Qwen 3 32B — Cloud, Groq','Qwen 3 32B — Cloud, Groq','Qwen 3 32B — Sky, Groq','Qwen 3 32B — Moln, Groq','Qwen 3 32B — 云端，Groq','Qwen 3 32B — 클라우드, Groq','Qwen 3 32B — クラウド、Groq'],
    'Application language': ['Lingua dell’applicazione','Idioma de la aplicación','Idioma da aplicação','Langue de l’application','Anwendungssprache','Applikationssprog','Programspråk','Programspråk','应用语言','앱 언어','アプリの言語'],
    'System default': ['Predefinita di sistema','Predeterminado del sistema','Predefinição do sistema','Par défaut du système','Systemstandard','Systemstandard','Systemstandard','Systemstandard','系统默认','시스템 기본값','システムのデフォルト'],
    'Changes apply immediately and are saved for the next launch.': ['Le modifiche vengono applicate subito e salvate per il prossimo avvio.','Los cambios se aplican inmediatamente y se guardan para el próximo inicio.','As alterações são aplicadas imediatamente e guardadas para o próximo arranque.','Les modifications s’appliquent immédiatement et sont enregistrées pour le prochain lancement.','Änderungen werden sofort angewendet und für den nächsten Start gespeichert.','Ændringer anvendes straks og gemmes til næste start.','Endringer tas i bruk umiddelbart og lagres til neste start.','Ändringar tillämpas direkt och sparas till nästa start.','更改会立即应用并保存供下次启动使用。','변경 사항은 즉시 적용되며 다음 실행을 위해 저장됩니다.','変更はすぐに適用され、次回起動時にも保持されます。'],
    'File':['File','Archivo','Ficheiro','Fichier','Datei','Filer','Fil','Arkiv','文件','파일','ファイル'], 'Edit':['Modifica','Editar','Editar','Modifier','Bearbeiten','Rediger','Rediger','Redigera','编辑','편집','編集'], 'View':['Vista','Ver','Ver','Affichage','Ansicht','Vis','Vis','Visa','查看','보기','表示'], 'Help':['Aiuto','Ayuda','Ajuda','Aide','Hilfe','Hjælp','Hjelp','Hjälp','帮助','도움말','ヘルプ'],
    'Library':['Libreria','Biblioteca','Biblioteca','Bibliothèque','Bibliothek','Bibliotek','Bibliotek','Bibliotek','资料库','라이브러리','ライブラリ'], 'Configuration':['Configurazione','Configuración','Configuração','Configuration','Konfiguration','Konfiguration','Konfigurasjon','Konfiguration','配置','설정','設定'],
    'Dashboard':['Dashboard','Panel','Painel','Tableau de bord','Übersicht','Oversigt','Oversikt','Översikt','仪表板','대시보드','ダッシュボード'], 'Recordings':['Registrazioni','Grabaciones','Gravações','Enregistrements','Aufnahmen','Optagelser','Opptak','Inspelningar','录音','녹음','録音'], 'Meetings':['Riunioni','Reuniones','Reuniões','Réunions','Besprechungen','Møder','Møter','Möten','会议','회의','会議'], 'Notes':['Note','Notas','Notas','Notes','Notizen','Noter','Notater','Anteckningar','笔记','노트','ノート'], 'Templates':['Modelli','Plantillas','Modelos','Modèles','Vorlagen','Skabeloner','Maler','Mallar','模板','템플릿','テンプレート'], 'Models':['Modelli','Modelos','Modelos','Modèles','Modelle','Modeller','Modeller','Modeller','模型','모델','モデル'], 'Engine':['Motore','Motor','Motor','Moteur','Engine','Motor','Motor','Motor','引擎','엔진','エンジン'], 'General':['Generale','General','Geral','Général','Allgemein','Generelt','Generelt','Allmänt','常规','일반','一般'],
    'Transcription':['Trascrizione','Transcripción','Transcrição','Transcription','Transkription','Transskription','Transkripsjon','Transkribering','转写','전사','文字起こし'],
    'Whisper models':['Modelli Whisper','Modelos de Whisper','Modelos Whisper','Modèles Whisper','Whisper-Modelle','Whisper-modeller','Whisper-modeller','Whisper-modeller','Whisper 模型','Whisper 모델','Whisperモデル'],
    'AI Notes':['Note IA','Notas de IA','Notas de IA','Notes IA','KI-Notizen','AI-noter','AI-notater','AI-anteckningar','AI 笔记','AI 노트','AIノート'],
    'Today':['Oggi','Hoy','Hoje','Aujourd’hui','Heute','I dag','I dag','I dag','今天','오늘','今日'], 'Start':['Avvia','Iniciar','Iniciar','Démarrer','Starten','Start','Start','Starta','开始','시작','開始'], 'Stop':['Interrompi','Detener','Parar','Arrêter','Stoppen','Stop','Stopp','Stoppa','停止','중지','停止'], 'Delete':['Elimina','Eliminar','Eliminar','Supprimer','Löschen','Slet','Slett','Ta bort','删除','삭제','削除'], 'Cancel':['Annulla','Cancelar','Cancelar','Annuler','Abbrechen','Annuller','Avbryt','Avbryt','取消','취소','キャンセル'], 'Save':['Salva','Guardar','Guardar','Enregistrer','Speichern','Gem','Lagre','Spara','保存','저장','保存'], 'Close':['Chiudi','Cerrar','Fechar','Fermer','Schließen','Luk','Lukk','Stäng','关闭','닫기','閉じる'], 'Add':['Aggiungi','Añadir','Adicionar','Ajouter','Hinzufügen','Tilføj','Legg til','Lägg till','添加','추가','追加'], 'Copy':['Copia','Copiar','Copiar','Copier','Kopieren','Kopiér','Kopier','Kopiera','复制','복사','コピー'],
    'Search recordings':['Cerca registrazioni','Buscar grabaciones','Pesquisar gravações','Rechercher des enregistrements','Aufnahmen suchen','Søg i optagelser','Søk i opptak','Sök inspelningar','搜索录音','녹음 검색','録音を検索'], 'Clear All':['Cancella tutto','Borrar todo','Limpar tudo','Tout effacer','Alle löschen','Ryd alle','Tøm alle','Rensa alla','全部清除','모두 지우기','すべて消去'], 'No recordings yet':['Nessuna registrazione','Aún no hay grabaciones','Ainda não há gravações','Aucun enregistrement','Noch keine Aufnahmen','Ingen optagelser endnu','Ingen opptak ennå','Inga inspelningar än','暂无录音','아직 녹음 없음','録音はまだありません'],
    'Appearance':['Aspetto','Apariencia','Aparência','Apparence','Darstellung','Udseende','Utseende','Utseende','外观','모양','外観'], 'System':['Sistema','Sistema','Sistema','Système','System','System','System','System','系统','시스템','システム'], 'Light':['Chiaro','Claro','Claro','Clair','Hell','Lys','Lys','Ljust','浅色','라이트','ライト'], 'Dark':['Scuro','Oscuro','Escuro','Sombre','Dunkel','Mørk','Mørk','Mörkt','深色','다크','ダーク'], 'Microphone':['Microfono','Micrófono','Microfone','Microphone','Mikrofon','Mikrofon','Mikrofon','Mikrofon','麦克风','마이크','マイク'], 'Language':['Lingua','Idioma','Idioma','Langue','Sprache','Sprog','Språk','Språk','语言','언어','言語'], 'Automatic updates':['Aggiornamenti automatici','Actualizaciones automáticas','Atualizações automáticas','Mises à jour automatiques','Automatische Updates','Automatiske opdateringer','Automatiske oppdateringer','Automatiska uppdateringar','自动更新','자동 업데이트','自動更新'], 'Permissions':['Autorizzazioni','Permisos','Permissões','Autorisations','Berechtigungen','Tilladelser','Tillatelser','Behörigheter','权限','권한','権限'], 'Support and local data':['Supporto e dati locali','Soporte y datos locales','Suporte e dados locais','Assistance et données locales','Support und lokale Daten','Support og lokale data','Støtte og lokale data','Support och lokala data','支持和本地数据','지원 및 로컬 데이터','サポートとローカルデータ'],
    'Finishing':['Completamento','Finalizando','A concluir','Finalisation','Abschluss','Afslutter','Fullfører','Slutför','正在完成','마무리 중','完了処理中'],
    'Meeting recording':['Riunione in registrazione','Grabando reunión','Reunião a ser gravada','Enregistrement de la réunion','Meeting wird aufgenommen','Møde optages','Møtet tas opp','Mötet spelas in','正在录制会议','회의 녹음 중','会議を録音中'],
    'Recording':['Registrazione','Grabando','A gravar','Enregistrement','Aufnahme','Optager','Tar opp','Spelar in','正在录音','녹음 중','録音中'], 'Transcribing':['Trascrizione','Transcribiendo','A transcrever','Transcription','Transkription','Transskriberer','Transkriberer','Transkriberar','正在转写','변환 중','文字起こし中'], 'Mic unavailable':['Microfono non disponibile','Micrófono no disponible','Microfone indisponível','Microphone indisponible','Mikrofon nicht verfügbar','Mikrofon ikke tilgængelig','Mikrofon utilgjengelig','Mikrofonen är inte tillgänglig','麦克风不可用','마이크를 사용할 수 없음','マイクを使用できません'], 'Mic blocked':['Microfono bloccato','Micrófono bloqueado','Microfone bloqueado','Microphone bloqué','Mikrofon blockiert','Mikrofon blokeret','Mikrofon blokkert','Mikrofonen blockerad','麦克风已被阻止','마이크 차단됨','マイクがブロックされました'], 'Recording meeting · click to stop':['Registrazione riunione · fai clic per interrompere','Grabando reunión · haz clic para detener','A gravar reunião · clique para parar','Réunion en cours · cliquez pour arrêter','Besprechungsaufnahme · zum Stoppen klicken','Optager møde · klik for at stoppe','Tar opp møte · klikk for å stoppe','Spelar in möte · klicka för att stoppa','正在录制会议 · 点击停止','회의 녹음 중 · 중지하려면 클릭','会議を録音中 · クリックして停止']
  };
  const sourceMessages = window.__CRUNCHY_I18N_CATALOGS__?.en || {};
  const catalogs = {};
  for (const language of supported) catalogs[language] = Object.fromEntries(Object.keys(sourceMessages).map(key => [key, key]));
  Object.assign(catalogs.en, Object.fromEntries(Object.keys(phrases).map(key => [key, key])));
  supported.slice(1).forEach((language, index) => {
    Object.assign(catalogs[language], Object.fromEntries(Object.entries(phrases).map(([key, values]) => [key, values[index]])));
  });
  let locale = 'en';
  const reverseKeys = new Map();
  for (const catalog of Object.values(catalogs)) {
    for (const [key, value] of Object.entries(catalog)) if (!reverseKeys.has(value)) reverseKeys.set(value, key);
  }
  const parameterMatchers = Object.keys(catalogs.en).flatMap(key => {
    if (!/\{\d+\}/.test(key)) return [];
    const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/\\\{(\d+)\\\}/g, '(.+?)');
    return [{ key, expression: new RegExp(`^${escaped}$`, 's') }];
  });
  const sourceKey = value => {
    if (catalogs.en[value]) return value;
    return reverseKeys.get(value) || value;
  };
  const userContentSelector = '[data-i18n],input,textarea,[contenteditable],.cm-editor,.muya,#history,#foldersList,#notesList,#calendarList,#meetingsList,#meetingTranscript,#meetingAiNotes,#templatesList';
  const normalize = value => { const code = String(value || '').toLowerCase().split('-')[0]; return supported.includes(code) ? code : 'en'; };
  function t(key, vars = {}) { let value = catalogs[locale]?.[key] || catalogs.en[key] || key; for (const [name, replacement] of Object.entries(vars)) value = value.replaceAll(`{${name}}`, () => String(replacement)); return value; }
  function translateValue(visible) {
    const exact = sourceKey(visible);
    if (catalogs.en[exact]) return t(exact);
    for (const { key, expression } of parameterMatchers) {
      const match = visible.match(expression);
      if (match) return t(key, Object.fromEntries(match.slice(1).map((value, index) => [index, value])));
    }
    return visible;
  }
  function translate(root = document) {
    const i18nElements = root.matches?.('[data-i18n]') ? [root, ...root.querySelectorAll('[data-i18n]')] : root.querySelectorAll('[data-i18n]');
    i18nElements.forEach(el => { el.textContent = t(el.dataset.i18n); });
    const walker = document.createTreeWalker(root.body || root, NodeFilter.SHOW_TEXT, {
      acceptNode: node => node.parentElement?.closest(userContentSelector) ? NodeFilter.FILTER_REJECT : NodeFilter.FILTER_ACCEPT,
    });
    const nodes = []; while (walker.nextNode()) nodes.push(walker.currentNode);
    for (const node of nodes) { const visible = node.nodeValue.trim(); const translated = translateValue(visible); if (translated !== visible) node.nodeValue = node.nodeValue.replace(visible, translated); }
    const attributeElements = root.matches?.('[placeholder],[title],[aria-label]') ? [root, ...root.querySelectorAll('[placeholder],[title],[aria-label]')] : root.querySelectorAll('[placeholder],[title],[aria-label]');
    attributeElements.forEach(el => { for (const attr of ['placeholder','title','aria-label']) { const visible = el.getAttribute(attr); const key = sourceKey(visible); if (key && catalogs.en[key]) el.setAttribute(attr, t(key)); } });
    document.documentElement.lang = locale;
  }
  function setLocale(value, systemLocale = navigator.language) { locale = value === 'system' ? normalize(systemLocale) : normalize(value); translate(); window.dispatchEvent(new CustomEvent('localechange', { detail: locale })); }
  window.i18n = { t, translate, setLocale, get locale() { return locale; }, supported, catalogs };
  const nativeDialogs = { alert: window.alert?.bind(window), confirm: window.confirm?.bind(window), prompt: window.prompt?.bind(window) };
  for (const name of Object.keys(nativeDialogs)) if (nativeDialogs[name]) window[name] = (message, ...args) => nativeDialogs[name](translateValue(String(message)), ...args);
  let observing = false;
  new MutationObserver(records => {
    if (observing) return;
    observing = true;
    for (const record of records) for (const node of record.addedNodes) {
      if (node.nodeType === Node.TEXT_NODE && !node.parentElement?.closest(userContentSelector)) { const visible = node.nodeValue.trim(); node.nodeValue = node.nodeValue.replace(visible, translateValue(visible)); }
      else if (node.nodeType === Node.ELEMENT_NODE) translate(node);
    }
    observing = false;
  }).observe(document.documentElement, { childList: true, subtree: true });
})();
