/* CrunchyMurmur renderer localisation. Keep catalogs structurally identical. */
(() => {
  const supported = ['en', 'it', 'es', 'pt', 'fr', 'de', 'da', 'no', 'sv', 'zh', 'ko', 'ja'];
  const phrases = {
    'Choose where transcription runs.': ['Scegli dove eseguire la trascrizione.','Elige dónde se ejecuta la transcripción.','Escolha onde a transcrição é executada.','Choisissez où la transcription est exécutée.','Wählen Sie, wo die Transkription ausgeführt wird.','Vælg, hvor transskriptionen kører.','Velg hvor transkripsjonen kjøres.','Välj var transkriberingen körs.','选择转录的运行位置。','전사를 실행할 위치를 선택하세요.','文字起こしの実行場所を選択します。'],
    'Models are stored in': ['I modelli sono archiviati in','Los modelos se almacenan en','Os modelos são armazenados em','Les modèles sont stockés dans','Modelle werden gespeichert unter','Modeller gemmes i','Modeller lagres i','Modeller lagras i','模型存储在','모델 저장 위치:','モデルの保存先:'],
    'Parakeet V3 is the recommended fast default for supported European languages.': ['Parakeet V3 è l’impostazione rapida consigliata per le lingue europee supportate.','Parakeet V3 es la opción rápida recomendada para los idiomas europeos compatibles.','O Parakeet V3 é a opção rápida recomendada para os idiomas europeus suportados.','Parakeet V3 est le choix rapide recommandé pour les langues européennes prises en charge.','Parakeet V3 ist die empfohlene schnelle Standardoption für unterstützte europäische Sprachen.','Parakeet V3 er det anbefalede hurtige standardvalg til understøttede europæiske sprog.','Parakeet V3 er det anbefalte raske standardvalget for støttede europeiske språk.','Parakeet V3 är det rekommenderade snabba standardvalet för europeiska språk som stöds.','对于支持的欧洲语言，Parakeet V3 是推荐的快速默认选项。','Parakeet V3는 지원되는 유럽 언어에 권장되는 빠른 기본 옵션입니다.','Parakeet V3は、対応するヨーロッパ言語向けの推奨高速デフォルトです。'],
    'Choose Whisper when you need broader language coverage, translation, or a custom GGML model.': ['Scegli Whisper quando servono più lingue, la traduzione o un modello GGML personalizzato.','Elige Whisper cuando necesites más idiomas, traducción o un modelo GGML personalizado.','Escolha o Whisper quando precisar de mais idiomas, tradução ou um modelo GGML personalizado.','Choisissez Whisper pour davantage de langues, la traduction ou un modèle GGML personnalisé.','Wählen Sie Whisper für mehr Sprachen, Übersetzung oder ein eigenes GGML-Modell.','Vælg Whisper, når du har brug for flere sprog, oversættelse eller en tilpasset GGML-model.','Velg Whisper når du trenger flere språk, oversettelse eller en tilpasset GGML-modell.','Välj Whisper när du behöver fler språk, översättning eller en anpassad GGML-modell.','需要更广泛的语言支持、翻译或自定义 GGML 模型时，请选择 Whisper。','더 폭넓은 언어 지원, 번역 또는 사용자 지정 GGML 모델이 필요하면 Whisper를 선택하세요.','より幅広い言語対応、翻訳、カスタムGGMLモデルが必要な場合はWhisperを選択してください。'],
    'Found': ['Trovato','Encontrado','Encontrado','Trouvé','Gefunden','Fundet','Funnet','Hittad','已找到','찾음','検出'],
    'Ready': ['Pronto','Listo','Pronto','Prêt','Bereit','Klar','Klar','Klar','就绪','준비됨','準備完了'],
    'whisper-cli is required before local transcription can run.': ['whisper-cli è necessario prima di poter eseguire la trascrizione locale.','whisper-cli es necesario para ejecutar la transcripción local.','O whisper-cli é necessário para executar a transcrição local.','whisper-cli est requis pour exécuter la transcription locale.','whisper-cli ist für die lokale Transkription erforderlich.','whisper-cli kræves for at køre lokal transskription.','whisper-cli kreves for å kjøre lokal transkripsjon.','whisper-cli krävs för att köra lokal transkribering.','运行本地转录前需要 whisper-cli。','로컬 전사를 실행하려면 whisper-cli가 필요합니다.','ローカル文字起こしの実行にはwhisper-cliが必要です。'],
    '(optional)': ['(facoltativo)','(opcional)','(opcional)','(facultatif)','(optional)','(valgfrit)','(valgfritt)','(valfritt)','（可选）','(선택 사항)','（任意）'],
    'Speed: Fastest': ['Velocità: massima','Velocidad: máxima','Velocidade: máxima','Vitesse : maximale','Geschwindigkeit: am höchsten','Hastighed: hurtigst','Hastighet: raskest','Hastighet: snabbast','速度：最快','속도: 가장 빠름','速度：最速'],
    'Speed: Very fast': ['Velocità: molto alta','Velocidad: muy alta','Velocidade: muito alta','Vitesse : très rapide','Geschwindigkeit: sehr schnell','Hastighed: meget hurtig','Hastighet: svært rask','Hastighet: mycket snabb','速度：非常快','속도: 매우 빠름','速度：非常に高速'],
    'Speed: Fast': ['Velocità: alta','Velocidad: alta','Velocidade: alta','Vitesse : rapide','Geschwindigkeit: schnell','Hastighed: hurtig','Hastighet: rask','Hastighet: snabb','速度：快','속도: 빠름','速度：高速'],
    'Speed: Medium': ['Velocità: media','Velocidad: media','Velocidade: média','Vitesse : moyenne','Geschwindigkeit: mittel','Hastighed: middel','Hastighet: middels','Hastighet: medel','速度：中等','속도: 보통','速度：標準'],
    'Speed: Slow': ['Velocità: bassa','Velocidad: baja','Velocidade: baixa','Vitesse : lente','Geschwindigkeit: langsam','Hastighed: langsom','Hastighet: langsom','Hastighet: långsam','速度：慢','속도: 느림','速度：低速'],
    'Speed: Slowest': ['Velocità: minima','Velocidad: mínima','Velocidade: mínima','Vitesse : la plus lente','Geschwindigkeit: am niedrigsten','Hastighed: langsomst','Hastighet: tregest','Hastighet: långsammast','速度：最慢','속도: 가장 느림','速度：最遅'],
    'Accuracy: Lowest': ['Precisione: minima','Precisión: mínima','Precisão: mínima','Précision : minimale','Genauigkeit: am niedrigsten','Nøjagtighed: lavest','Nøyaktighet: lavest','Noggrannhet: lägst','准确度：最低','정확도: 가장 낮음','精度：最低'],
    'Accuracy: Low': ['Precisione: bassa','Precisión: baja','Precisão: baixa','Précision : faible','Genauigkeit: niedrig','Nøjagtighed: lav','Nøyaktighet: lav','Noggrannhet: låg','准确度：较低','정확도: 낮음','精度：低い'],
    'Accuracy: OK': ['Precisione: discreta','Precisión: aceptable','Precisão: razoável','Précision : correcte','Genauigkeit: okay','Nøjagtighed: rimelig','Nøyaktighet: grei','Noggrannhet: godtagbar','准确度：尚可','정확도: 보통','精度：標準'],
    'Accuracy: Good': ['Precisione: buona','Precisión: buena','Precisão: boa','Précision : bonne','Genauigkeit: gut','Nøjagtighed: god','Nøyaktighet: god','Noggrannhet: bra','准确度：良好','정확도: 좋음','精度：良好'],
    'Accuracy: High': ['Precisione: alta','Precisión: alta','Precisão: alta','Précision : élevée','Genauigkeit: hoch','Nøjagtighed: høj','Nøyaktighet: høy','Noggrannhet: hög','准确度：高','정확도: 높음','精度：高い'],
    'Accuracy: Excellent': ['Precisione: eccellente','Precisión: excelente','Precisão: excelente','Précision : excellente','Genauigkeit: ausgezeichnet','Nøjagtighed: fremragende','Nøyaktighet: utmerket','Noggrannhet: utmärkt','准确度：极佳','정확도: 매우 높음','精度：非常に高い'],
    'Accuracy: Best': ['Precisione: massima','Precisión: máxima','Precisão: máxima','Précision : maximale','Genauigkeit: am höchsten','Nøjagtighed: højest','Nøyaktighet: høyest','Noggrannhet: högst','准确度：最高','정확도: 가장 높음','精度：最高'],
    'Local models': ['Modelli locali','Modelos locales','Modelos locais','Modèles locaux','Lokale Modelle','Lokale modeller','Lokale modeller','Lokala modeller','本地模型','로컬 모델','ローカルモデル'],
    'Parakeet V3 (fast local)': ['Parakeet V3 (locale veloce)','Parakeet V3 (local rápido)','Parakeet V3 (local rápido)','Parakeet V3 (local rapide)','Parakeet V3 (schnell und lokal)','Parakeet V3 (hurtig lokal)','Parakeet V3 (rask lokal)','Parakeet V3 (snabb lokal)','Parakeet V3（快速本地）','Parakeet V3(빠른 로컬)','Parakeet V3（高速ローカル）'],
    'Whisper (widest languages)': ['Whisper (più lingue)','Whisper (más idiomas)','Whisper (mais idiomas)','Whisper (le plus de langues)','Whisper (größte Sprachauswahl)','Whisper (flest sprog)','Whisper (flest språk)','Whisper (flest språk)','Whisper（语言最广）','Whisper(가장 폭넓은 언어)','Whisper（最多言語）'],
    'Checking the bundled local engine...': ['Verifica del motore locale incluso...','Comprobando el motor local incluido...','A verificar o motor local incluído...','Vérification du moteur local inclus...','Mitgelieferte lokale Engine wird geprüft...','Kontrollerer den medfølgende lokale motor...','Kontrollerer den medfølgende lokale motoren...','Kontrollerar den medföljande lokala motorn...','正在检查内置本地引擎...','번들 로컬 엔진을 확인하는 중...','同梱ローカルエンジンを確認中...'],
    'The bundled local transcription engine is missing.': ['Il motore di trascrizione locale incluso non è disponibile.','Falta el motor de transcripción local incluido.','O motor de transcrição local incluído está em falta.','Le moteur de transcription local inclus est absent.','Die mitgelieferte lokale Transkriptions-Engine fehlt.','Den medfølgende lokale transskriptionsmotor mangler.','Den medfølgende lokale transkripsjonsmotoren mangler.','Den medföljande lokala transkriberingsmotorn saknas.','缺少内置本地转录引擎。','번들 로컬 전사 엔진이 없습니다.','同梱ローカル文字起こしエンジンがありません。'],
    'Parakeet V3 is loaded and ready.': ['Parakeet V3 è caricato e pronto.','Parakeet V3 está cargado y listo.','O Parakeet V3 está carregado e pronto.','Parakeet V3 est chargé et prêt.','Parakeet V3 ist geladen und bereit.','Parakeet V3 er indlæst og klar.','Parakeet V3 er lastet og klar.','Parakeet V3 är inläst och klart.','Parakeet V3 已加载并就绪。','Parakeet V3가 로드되어 준비되었습니다.','Parakeet V3を読み込み、準備ができました。'],
    'Parakeet V3 is ready and will load with your next recording.': ['Parakeet V3 è pronto e verrà caricato alla prossima registrazione.','Parakeet V3 está listo y se cargará con la próxima grabación.','O Parakeet V3 está pronto e será carregado na próxima gravação.','Parakeet V3 est prêt et sera chargé lors du prochain enregistrement.','Parakeet V3 ist bereit und wird bei der nächsten Aufnahme geladen.','Parakeet V3 er klar og indlæses ved din næste optagelse.','Parakeet V3 er klart og lastes ved neste opptak.','Parakeet V3 är klart och läses in vid nästa inspelning.','Parakeet V3 已就绪，将在下次录音时加载。','Parakeet V3가 준비되었으며 다음 녹음 때 로드됩니다.','Parakeet V3は準備済みで、次回の録音時に読み込まれます。'],
    '25 European languages': ['25 lingue europee','25 idiomas europeos','25 idiomas europeus','25 langues européennes','25 europäische Sprachen','25 europæiske sprog','25 europeiske språk','25 europeiska språk','25 种欧洲语言','25개 유럽 언어','ヨーロッパの25言語'],
    'Parakeet is the fast recommended local engine for 25 European languages.': ['Parakeet è il motore locale veloce consigliato per 25 lingue europee.','Parakeet es el motor local rápido recomendado para 25 idiomas europeos.','O Parakeet é o motor local rápido recomendado para 25 idiomas europeus.','Parakeet est le moteur local rapide recommandé pour 25 langues européennes.','Parakeet ist die empfohlene schnelle lokale Engine für 25 europäische Sprachen.','Parakeet er den anbefalede hurtige lokale motor til 25 europæiske sprog.','Parakeet er den anbefalte raske lokale motoren for 25 europeiske språk.','Parakeet är den rekommenderade snabba lokala motorn för 25 europeiska språk.','Parakeet 是推荐的快速本地引擎，支持 25 种欧洲语言。','Parakeet은 25개 유럽 언어를 지원하는 권장 고속 로컬 엔진입니다.','Parakeetはヨーロッパの25言語に対応する推奨の高速ローカルエンジンです。'],
    'Whisper provides the widest language support and optional translation.': ['Whisper offre il supporto linguistico più ampio e la traduzione facoltativa.','Whisper ofrece la mayor compatibilidad de idiomas y traducción opcional.','O Whisper oferece o suporte de idiomas mais amplo e tradução opcional.','Whisper offre la plus large prise en charge linguistique et une traduction facultative.','Whisper bietet die größte Sprachauswahl und optionale Übersetzung.','Whisper giver den bredeste sprogunderstøttelse og valgfri oversættelse.','Whisper gir den bredeste språkstøtten og valgfri oversettelse.','Whisper ger det bredaste språkstödet och valfri översättning.','Whisper 提供最广泛的语言支持和可选翻译。','Whisper는 가장 폭넓은 언어 지원과 선택적 번역을 제공합니다.','Whisperは最も幅広い言語対応と任意の翻訳機能を提供します。'],
    'Fast, high-accuracy transcription for 25 European languages. Language is detected automatically.': ['Trascrizione rapida e molto accurata per 25 lingue europee. La lingua viene rilevata automaticamente.','Transcripción rápida y muy precisa para 25 idiomas europeos. El idioma se detecta automáticamente.','Transcrição rápida e altamente precisa para 25 idiomas europeus. O idioma é detetado automaticamente.','Transcription rapide et très précise pour 25 langues européennes. La langue est détectée automatiquement.','Schnelle, hochpräzise Transkription für 25 europäische Sprachen. Die Sprache wird automatisch erkannt.','Hurtig transskription med høj nøjagtighed til 25 europæiske sprog. Sproget registreres automatisk.','Rask transkripsjon med høy nøyaktighet for 25 europeiske språk. Språket oppdages automatisk.','Snabb transkribering med hög noggrannhet för 25 europeiska språk. Språket identifieras automatiskt.','支持 25 种欧洲语言的快速高精度转录。语言会自动检测。','25개 유럽 언어를 빠르고 정확하게 전사합니다. 언어는 자동으로 감지됩니다.','ヨーロッパの25言語を高速かつ高精度で文字起こしします。言語は自動検出されます。'],
    'Manage local models': ['Gestisci i modelli locali','Administrar modelos locales','Gerir modelos locais','Gérer les modèles locaux','Lokale Modelle verwalten','Administrer lokale modeller','Administrer lokale modeller','Hantera lokala modeller','管理本地模型','로컬 모델 관리','ローカルモデルを管理'],
    'Parakeet detects language automatically. Choose Whisper for Turkish, Arabic, Hindi, Japanese, Korean, Chinese, Norwegian, and other unsupported languages.': ['Parakeet rileva automaticamente la lingua. Scegli Whisper per turco, arabo, hindi, giapponese, coreano, cinese, norvegese e altre lingue non supportate.','Parakeet detecta el idioma automáticamente. Elige Whisper para turco, árabe, hindi, japonés, coreano, chino, noruego y otros idiomas no compatibles.','O Parakeet deteta o idioma automaticamente. Escolha o Whisper para turco, árabe, hindi, japonês, coreano, chinês, norueguês e outros idiomas não suportados.','Parakeet détecte automatiquement la langue. Choisissez Whisper pour le turc, l’arabe, l’hindi, le japonais, le coréen, le chinois, le norvégien et les autres langues non prises en charge.','Parakeet erkennt die Sprache automatisch. Verwenden Sie Whisper für Türkisch, Arabisch, Hindi, Japanisch, Koreanisch, Chinesisch, Norwegisch und andere nicht unterstützte Sprachen.','Parakeet registrerer sproget automatisk. Vælg Whisper til tyrkisk, arabisk, hindi, japansk, koreansk, kinesisk, norsk og andre ikke-understøttede sprog.','Parakeet oppdager språket automatisk. Velg Whisper for tyrkisk, arabisk, hindi, japansk, koreansk, kinesisk, norsk og andre språk som ikke støttes.','Parakeet identifierar språket automatiskt. Välj Whisper för turkiska, arabiska, hindi, japanska, koreanska, kinesiska, norska och andra språk som inte stöds.','Parakeet 会自动检测语言。土耳其语、阿拉伯语、印地语、日语、韩语、中文、挪威语及其他不支持的语言请使用 Whisper。','Parakeet은 언어를 자동으로 감지합니다. 터키어, 아랍어, 힌디어, 일본어, 한국어, 중국어, 노르웨이어 및 기타 지원되지 않는 언어에는 Whisper를 선택하세요.','Parakeetは言語を自動検出します。トルコ語、アラビア語、ヒンディー語、日本語、韓国語、中国語、ノルウェー語など、未対応の言語にはWhisperを選択してください。'],
    'Checking bundled whisper.cpp...': ['Verifica di whisper.cpp incluso...','Comprobando whisper.cpp incluido...','A verificar o whisper.cpp incluído...','Vérification de whisper.cpp inclus...','Mitgeliefertes whisper.cpp wird geprüft...','Kontrollerer den medfølgende whisper.cpp...','Kontrollerer medfølgende whisper.cpp...','Kontrollerar medföljande whisper.cpp...','正在检查内置 whisper.cpp...','번들 whisper.cpp를 확인하는 중...','同梱のwhisper.cppを確認中...'],
    'Bundled whisper.cpp is ready.': ['whisper.cpp incluso è pronto.','whisper.cpp incluido está listo.','O whisper.cpp incluído está pronto.','whisper.cpp inclus est prêt.','Das mitgelieferte whisper.cpp ist bereit.','Den medfølgende whisper.cpp er klar.','Medfølgende whisper.cpp er klar.','Medföljande whisper.cpp är klar.','内置 whisper.cpp 已就绪。','번들 whisper.cpp가 준비되었습니다.','同梱のwhisper.cppを利用できます。'],
    'Use a custom whisper.cpp build': ['Usa una build personalizzata di whisper.cpp','Usar una compilación personalizada de whisper.cpp','Usar uma compilação personalizada do whisper.cpp','Utiliser une version personnalisée de whisper.cpp','Eigenen whisper.cpp-Build verwenden','Brug en tilpasset whisper.cpp-build','Bruk en tilpasset whisper.cpp-versjon','Använd en anpassad whisper.cpp-version','使用自定义 whisper.cpp 构建','사용자 지정 whisper.cpp 빌드 사용','カスタムwhisper.cppビルドを使用'],
    'Custom whisper-cli executable': ['Eseguibile whisper-cli personalizzato','Ejecutable whisper-cli personalizado','Executável whisper-cli personalizado','Exécutable whisper-cli personnalisé','Benutzerdefinierte whisper-cli-Datei','Tilpasset whisper-cli-program','Tilpasset whisper-cli-program','Anpassad whisper-cli-körfil','自定义 whisper-cli 可执行文件','사용자 지정 whisper-cli 실행 파일','カスタムwhisper-cli実行ファイル'],
    'CrunchyMurmur includes whisper.cpp. Use Browse only to override the bundled runtime with another compatible build.': ['CrunchyMurmur include whisper.cpp. Usa Sfoglia solo per sostituire il runtime incluso con un’altra build compatibile.','CrunchyMurmur incluye whisper.cpp. Usa Examinar solo para sustituir el entorno incluido por otra compilación compatible.','O CrunchyMurmur inclui o whisper.cpp. Use Procurar apenas para substituir o runtime incluído por outra compilação compatível.','CrunchyMurmur inclut whisper.cpp. Utilisez Parcourir uniquement pour remplacer le moteur inclus par une autre version compatible.','CrunchyMurmur enthält whisper.cpp. Verwenden Sie Durchsuchen nur, um die mitgelieferte Laufzeit durch einen anderen kompatiblen Build zu ersetzen.','CrunchyMurmur inkluderer whisper.cpp. Brug kun Gennemse for at erstatte den medfølgende runtime med en anden kompatibel build.','CrunchyMurmur inkluderer whisper.cpp. Bruk Bla gjennom bare for å erstatte den medfølgende kjøretiden med en annen kompatibel versjon.','CrunchyMurmur innehåller whisper.cpp. Använd endast Bläddra för att ersätta den medföljande körmiljön med en annan kompatibel version.','CrunchyMurmur 已内置 whisper.cpp。仅在需要用其他兼容构建替换内置运行时时使用“浏览”。','CrunchyMurmur에는 whisper.cpp가 포함되어 있습니다. 다른 호환 빌드로 번들 런타임을 재정의할 때만 찾아보기를 사용하세요.','CrunchyMurmurにはwhisper.cppが含まれています。別の互換ビルドで同梱ランタイムを置き換える場合にのみ「参照」を使用してください。'],
    'Checking local acceleration...': ['Verifica dell’accelerazione locale...','Comprobando la aceleración local...','A verificar a aceleração local...','Vérification de l’accélération locale...','Lokale Beschleunigung wird geprüft...','Kontrollerer lokal acceleration...','Kontrollerer lokal akselerasjon...','Kontrollerar lokal acceleration...','正在检查本地加速...','로컬 가속을 확인하는 중...','ローカルアクセラレーションを確認中...'],
    'Persistent acceleration is active. The model stays loaded between transcriptions.': ['L’accelerazione persistente è attiva. Il modello resta caricato tra una trascrizione e l’altra.','La aceleración persistente está activa. El modelo permanece cargado entre transcripciones.','A aceleração persistente está ativa. O modelo permanece carregado entre transcrições.','L’accélération persistante est active. Le modèle reste chargé entre les transcriptions.','Die dauerhafte Beschleunigung ist aktiv. Das Modell bleibt zwischen Transkriptionen geladen.','Vedvarende acceleration er aktiv. Modellen forbliver indlæst mellem transskriptioner.','Vedvarende akselerasjon er aktiv. Modellen forblir lastet mellom transkripsjoner.','Beständig acceleration är aktiv. Modellen förblir inläst mellan transkriberingar.','持久加速已启用。模型会在两次转录之间保持加载。','영구 가속이 활성화되었습니다. 전사 사이에도 모델이 로드된 상태로 유지됩니다.','常駐アクセラレーションが有効です。文字起こしの間もモデルは読み込まれたままです。'],
    'Persistent acceleration is available and will start with your next recording.': ['L’accelerazione persistente è disponibile e si avvierà con la prossima registrazione.','La aceleración persistente está disponible y se iniciará con la próxima grabación.','A aceleração persistente está disponível e será iniciada na próxima gravação.','L’accélération persistante est disponible et démarrera lors du prochain enregistrement.','Die dauerhafte Beschleunigung ist verfügbar und startet mit der nächsten Aufnahme.','Vedvarende acceleration er tilgængelig og starter ved din næste optagelse.','Vedvarende akselerasjon er tilgjengelig og starter med neste opptak.','Beständig acceleration är tillgänglig och startar med nästa inspelning.','持久加速可用，将在下次录音时启动。','영구 가속을 사용할 수 있으며 다음 녹음 시 시작됩니다.','常駐アクセラレーションを利用できます。次回の録音時に開始します。'],
    'Persistent acceleration is unavailable. Transcription still works, but the model reloads for each recording.': ['L’accelerazione persistente non è disponibile. La trascrizione funziona comunque, ma il modello viene ricaricato per ogni registrazione.','La aceleración persistente no está disponible. La transcripción sigue funcionando, pero el modelo se vuelve a cargar en cada grabación.','A aceleração persistente não está disponível. A transcrição continua a funcionar, mas o modelo é recarregado em cada gravação.','L’accélération persistante n’est pas disponible. La transcription fonctionne toujours, mais le modèle est rechargé pour chaque enregistrement.','Die dauerhafte Beschleunigung ist nicht verfügbar. Die Transkription funktioniert weiterhin, aber das Modell wird für jede Aufnahme neu geladen.','Vedvarende acceleration er ikke tilgængelig. Transskription virker stadig, men modellen genindlæses for hver optagelse.','Vedvarende akselerasjon er ikke tilgjengelig. Transkripsjon fungerer fortsatt, men modellen lastes inn på nytt for hvert opptak.','Beständig acceleration är inte tillgänglig. Transkribering fungerar fortfarande, men modellen läses in på nytt för varje inspelning.','持久加速不可用。转录仍可正常工作，但每次录音都需要重新加载模型。','영구 가속을 사용할 수 없습니다. 전사는 계속 작동하지만 녹음할 때마다 모델을 다시 로드합니다.','常駐アクセラレーションは利用できません。文字起こしは動作しますが、録音ごとにモデルが再読み込みされます。'],
    'Minimal — fastest supported reasoning': ['Minimo — ragionamento supportato più veloce','Mínimo — razonamiento compatible más rápido','Mínimo — raciocínio suportado mais rápido','Minimal — raisonnement pris en charge le plus rapide','Minimal — schnellstes unterstütztes Denken','Minimal — hurtigste understøttede ræsonnering','Minimal — raskeste støttede resonnering','Minimal — snabbaste resonemang som stöds','最低 — 最快的受支持推理','최소 — 가장 빠른 지원 추론','最小 — サポートされる最速の推論'],
    'Claude Opus 4.5 (highest quality)': ['Claude Opus 4.5 (qualità massima)','Claude Opus 4.5 (máxima calidad)','Claude Opus 4.5 (qualidade máxima)','Claude Opus 4.5 (qualité maximale)','Claude Opus 4.5 (höchste Qualität)','Claude Opus 4.5 (højeste kvalitet)','Claude Opus 4.5 (høyeste kvalitet)','Claude Opus 4.5 (högsta kvalitet)','Claude Opus 4.5（最高质量）','Claude Opus 4.5(최고 품질)','Claude Opus 4.5（最高品質）'],
    'Claude Sonnet 4.6 (recommended)': ['Claude Sonnet 4.6 (consigliato)','Claude Sonnet 4.6 (recomendado)','Claude Sonnet 4.6 (recomendado)','Claude Sonnet 4.6 (recommandé)','Claude Sonnet 4.6 (empfohlen)','Claude Sonnet 4.6 (anbefalet)','Claude Sonnet 4.6 (anbefalt)','Claude Sonnet 4.6 (rekommenderas)','Claude Sonnet 4.6（推荐）','Claude Sonnet 4.6(권장)','Claude Sonnet 4.6（推奨）'],
    'Claude Haiku 4.5 (fastest, cheapest)': ['Claude Haiku 4.5 (più veloce ed economico)','Claude Haiku 4.5 (más rápido y económico)','Claude Haiku 4.5 (mais rápido e económico)','Claude Haiku 4.5 (le plus rapide et économique)','Claude Haiku 4.5 (am schnellsten und günstigsten)','Claude Haiku 4.5 (hurtigst og billigst)','Claude Haiku 4.5 (raskest og billigst)','Claude Haiku 4.5 (snabbast och billigast)','Claude Haiku 4.5（最快、最便宜）','Claude Haiku 4.5(가장 빠르고 저렴함)','Claude Haiku 4.5（最速・最安）'],
    'GPT-4o (recommended)': ['GPT-4o (consigliato)','GPT-4o (recomendado)','GPT-4o (recomendado)','GPT-4o (recommandé)','GPT-4o (empfohlen)','GPT-4o (anbefalet)','GPT-4o (anbefalt)','GPT-4o (rekommenderas)','GPT-4o（推荐）','GPT-4o(권장)','GPT-4o（推奨）'],
    'GPT-4o mini (fastest, cheapest)': ['GPT-4o mini (più veloce ed economico)','GPT-4o mini (más rápido y económico)','GPT-4o mini (mais rápido e económico)','GPT-4o mini (le plus rapide et économique)','GPT-4o mini (am schnellsten und günstigsten)','GPT-4o mini (hurtigst og billigst)','GPT-4o mini (raskest og billigst)','GPT-4o mini (snabbast och billigast)','GPT-4o mini（最快、最便宜）','GPT-4o mini(가장 빠르고 저렴함)','GPT-4o mini（最速・最安）'],
    'GPT OSS 120B (recommended)': ['GPT OSS 120B (consigliato)','GPT OSS 120B (recomendado)','GPT OSS 120B (recomendado)','GPT OSS 120B (recommandé)','GPT OSS 120B (empfohlen)','GPT OSS 120B (anbefalet)','GPT OSS 120B (anbefalt)','GPT OSS 120B (rekommenderas)','GPT OSS 120B（推荐）','GPT OSS 120B(권장)','GPT OSS 120B（推奨）'],
    'Llama 3.1 8B (fastest)': ['Llama 3.1 8B (più veloce)','Llama 3.1 8B (más rápido)','Llama 3.1 8B (mais rápido)','Llama 3.1 8B (le plus rapide)','Llama 3.1 8B (am schnellsten)','Llama 3.1 8B (hurtigst)','Llama 3.1 8B (raskest)','Llama 3.1 8B (snabbast)','Llama 3.1 8B（最快）','Llama 3.1 8B(가장 빠름)','Llama 3.1 8B（最速）'],
    'Llama 4 Scout 17B': ['Llama 4 Scout 17B','Llama 4 Scout 17B','Llama 4 Scout 17B','Llama 4 Scout 17B','Llama 4 Scout 17B','Llama 4 Scout 17B','Llama 4 Scout 17B','Llama 4 Scout 17B','Llama 4 Scout 17B','Llama 4 Scout 17B','Llama 4 Scout 17B'],
    'Qwen 3 32B': ['Qwen 3 32B','Qwen 3 32B','Qwen 3 32B','Qwen 3 32B','Qwen 3 32B','Qwen 3 32B','Qwen 3 32B','Qwen 3 32B','Qwen 3 32B','Qwen 3 32B','Qwen 3 32B'],
    'CLI default (recommended)': ['Predefinito della CLI (consigliato)','Predeterminado de la CLI (recomendado)','Predefinição da CLI (recomendado)','Valeur par défaut de la CLI (recommandée)','CLI-Standard (empfohlen)','CLI-standard (anbefalet)','CLI-standard (anbefalt)','CLI-standard (rekommenderas)','CLI 默认值（推荐）','CLI 기본값(권장)','CLI のデフォルト（推奨）'],
    'Maximum — highest reasoning depth': ['Massimo — massima profondità di ragionamento','Máximo — máxima profundidad de razonamiento','Máximo — maior profundidade de raciocínio','Maximum — profondeur de raisonnement maximale','Maximum — höchste Denktiefe','Maksimum — højeste ræsonneringsdybde','Maksimum — høyeste resonneringsdybde','Maximum — högsta resonemangsdjup','最大 — 最高推理深度','최대 — 가장 높은 추론 깊이','最大 — 最高の推論深度'],
    'Ultra — maximum reasoning with delegation': ['Ultra — ragionamento massimo con delega','Ultra — razonamiento máximo con delegación','Ultra — raciocínio máximo com delegação','Ultra — raisonnement maximal avec délégation','Ultra — maximales Denken mit Delegierung','Ultra — maksimal ræsonnering med delegering','Ultra — maksimal resonnering med delegering','Ultra — maximalt resonemang med delegering','超强 — 最高推理并自动委派','울트라 — 위임을 포함한 최대 추론','ウルトラ — 委任を伴う最大推論'],
    'Effective configuration: {0}': ['Configurazione effettiva: {0}','Configuración efectiva: {0}','Configuração efetiva: {0}','Configuration effective : {0}','Wirksame Konfiguration: {0}','Aktiv konfiguration: {0}','Gjeldende konfigurasjon: {0}','Aktiv konfiguration: {0}','生效配置：{0}','적용 구성: {0}','有効な構成: {0}'],
    'Effort': ['Impegno','Esfuerzo','Esforço','Effort','Aufwand','Indsats','Innsats','Ansträngning','投入程度','작업 강도','処理強度'],
    'Extra high — slowest, highest subscription usage': ['Molto alto — più lento, massimo utilizzo dell’abbonamento','Muy alto — el más lento y con mayor uso de la suscripción','Muito alto — mais lento e com maior utilização da subscrição','Très élevé — le plus lent et l’utilisation d’abonnement la plus élevée','Sehr hoch — am langsamsten, höchste Abonnementnutzung','Ekstra høj — langsomst, højeste abonnementsforbrug','Ekstra høy — tregest, høyest abonnementsbruk','Extra hög — långsammast, högst abonnemangsanvändning','超高 — 最慢，订阅用量最高','매우 높음 — 가장 느리고 구독 사용량이 가장 높음','最高 — 最も遅く、サブスクリプション使用量が最大'],
    'High — better for complex transcripts': ['Alto — migliore per trascrizioni complesse','Alto — mejor para transcripciones complejas','Alto — melhor para transcrições complexas','Élevé — mieux adapté aux transcriptions complexes','Hoch — besser für komplexe Transkripte','Høj — bedre til komplekse transskriptioner','Høy — bedre for komplekse transkripsjoner','Hög — bättre för komplexa transkriptioner','高 — 更适合复杂转录','높음 — 복잡한 전사에 적합','高 — 複雑な文字起こしに適する'],
    'Low — fastest, lowest subscription usage': ['Basso — più veloce, minimo utilizzo dell’abbonamento','Bajo — el más rápido y con menor uso de la suscripción','Baixo — mais rápido e com menor utilização da subscrição','Faible — le plus rapide et l’utilisation d’abonnement la plus faible','Niedrig — am schnellsten, geringste Abonnementnutzung','Lav — hurtigst, laveste abonnementsforbrug','Lav — raskest, lavest abonnementsbruk','Låg — snabbast, lägst abonnemangsanvändning','低 — 最快，订阅用量最低','낮음 — 가장 빠르고 구독 사용량이 가장 적음','低 — 最速でサブスクリプション使用量が最小'],
    'Medium — recommended for summaries': ['Medio — consigliato per i riepiloghi','Medio — recomendado para resúmenes','Médio — recomendado para resumos','Moyen — recommandé pour les résumés','Mittel — für Zusammenfassungen empfohlen','Mellem — anbefales til resuméer','Middels — anbefalt for sammendrag','Medel — rekommenderas för sammanfattningar','中 — 建议用于摘要','중간 — 요약에 권장','中 — 要約に推奨'],
    'Reasoning effort': ['Impegno di ragionamento','Esfuerzo de razonamiento','Esforço de raciocínio','Effort de raisonnement','Denkaufwand','Ræsonneringsindsats','Resonneringsinnsats','Resonemangsnivå','推理强度','추론 강도','推論強度'],
    'Anthropic fallback sends transcript text, but not audio, to Anthropic. It requires an Anthropic account and API key. Provider charges may apply.': ['Il fallback Anthropic invia ad Anthropic il testo della trascrizione, ma non l’audio. Richiede un account Anthropic e una chiave API. Potrebbero essere applicati costi.','La alternativa de Anthropic envía a Anthropic el texto de la transcripción, pero no el audio. Requiere una cuenta de Anthropic y una clave de API. Puede haber cargos.','A alternativa Anthropic envia o texto da transcrição, mas não o áudio, para a Anthropic. Requer uma conta Anthropic e uma chave de API. Poderão aplicar-se custos.','Le recours à Anthropic envoie le texte de la transcription, mais pas l’audio, à Anthropic. Il nécessite un compte Anthropic et une clé API. Des frais peuvent s’appliquer.','Die Anthropic-Ausweichoption sendet den Transkripttext, nicht jedoch das Audio, an Anthropic. Ein Anthropic-Konto und ein API-Schlüssel sind erforderlich. Kosten können anfallen.','Anthropic-reserveløsningen sender transskriptionsteksten, men ikke lyden, til Anthropic. Det kræver en Anthropic-konto og API-nøgle. Der kan forekomme udgifter.','Anthropic-reserveløsningen sender transkripsjonsteksten, men ikke lyden, til Anthropic. Det krever en Anthropic-konto og API-nøkkel. Kostnader kan påløpe.','Anthropic-alternativet skickar transkriptionstexten, men inte ljudet, till Anthropic. Ett Anthropic-konto och en API-nyckel krävs. Kostnader kan tillkomma.','Anthropic 回退会将转录文本（不含音频）发送给 Anthropic。需要 Anthropic 帐户和 API 密钥。可能产生费用。','Anthropic 대체 처리는 오디오를 제외한 전사 텍스트를 Anthropic에 보냅니다. Anthropic 계정과 API 키가 필요하며 요금이 부과될 수 있습니다.','Anthropic フォールバックでは、音声ではなく文字起こしテキストを Anthropic に送信します。Anthropic アカウントと API キーが必要です。料金が発生する場合があります。'],
    'AI formatting removes filler words and false starts, fixes punctuation and capitalization, and turns spoken lists into bullets. It does not change the intended meaning.': ['La formattazione AI rimuove intercalari e false partenze, corregge punteggiatura e maiuscole e trasforma gli elenchi dettati in punti elenco. Non cambia il significato voluto.','El formato con IA elimina muletillas y falsos comienzos, corrige la puntuación y las mayúsculas y convierte las listas habladas en viñetas. No cambia el significado pretendido.','A formatação por IA remove palavras de preenchimento e falsos começos, corrige a pontuação e as maiúsculas e transforma listas faladas em marcadores. Não altera o significado pretendido.','La mise en forme par IA supprime les mots de remplissage et les faux départs, corrige la ponctuation et les majuscules, et transforme les listes dictées en puces. Elle ne modifie pas le sens voulu.','Die KI-Formatierung entfernt Füllwörter und Fehlansätze, korrigiert Zeichensetzung und Großschreibung und wandelt gesprochene Listen in Aufzählungen um. Die beabsichtigte Bedeutung bleibt unverändert.','AI-formatering fjerner fyldord og fejlstarter, retter tegnsætning og store bogstaver og omdanner talte lister til punktlister. Den ændrer ikke den tilsigtede betydning.','KI-formatering fjerner fyllord og feilstarter, retter tegnsetting og store bokstaver og gjør talte lister om til punktlister. Den endrer ikke den tiltenkte betydningen.','AI-formatering tar bort utfyllnadsord och omstarter, rättar interpunktion och versaler och omvandlar talade listor till punktlistor. Den ändrar inte den avsedda betydelsen.','AI 格式化会删除填充词和重新开始的片段，修正标点和大小写，并将口述列表转为项目符号。它不会改变原意。','AI 형식 지정은 추임새와 잘못 시작한 부분을 제거하고 문장 부호와 대소문자를 바로잡으며 구술 목록을 글머리표로 변환합니다. 의도한 의미는 바꾸지 않습니다.','AI フォーマットは、フィラーや言い直しを削除し、句読点と大文字・小文字を修正し、口頭のリストを箇条書きに変換します。意図した意味は変更しません。'],
    'Cloud processing sends transcript text, but not audio, to Groq. It requires a Groq account and API key; no model download or local storage is needed. Provider charges may apply.': ['L’elaborazione nel cloud invia a Groq il testo della trascrizione, ma non l’audio. Richiede un account Groq e una chiave API; non servono download di modelli né spazio locale. Potrebbero essere applicati costi.','El procesamiento en la nube envía a Groq el texto de la transcripción, pero no el audio. Requiere una cuenta de Groq y una clave de API; no hace falta descargar modelos ni usar almacenamiento local. Puede haber cargos.','O processamento na nuvem envia o texto da transcrição, mas não o áudio, para a Groq. Requer uma conta Groq e uma chave de API; não é necessário transferir modelos nem usar armazenamento local. Poderão aplicar-se custos.','Le traitement dans le cloud envoie le texte de la transcription, mais pas l’audio, à Groq. Il nécessite un compte Groq et une clé API ; aucun téléchargement de modèle ni stockage local n’est requis. Des frais peuvent s’appliquer.','Bei der Cloud-Verarbeitung wird der Transkripttext, nicht jedoch das Audio, an Groq gesendet. Ein Groq-Konto und ein API-Schlüssel sind erforderlich; Modelldownload und lokaler Speicher sind nicht nötig. Kosten können anfallen.','Cloudbehandling sender transskriptionsteksten, men ikke lyden, til Groq. Det kræver en Groq-konto og API-nøgle; der kræves ingen modeldownload eller lokal lagerplads. Der kan forekomme udgifter.','Skybehandling sender transkripsjonsteksten, men ikke lyden, til Groq. Det krever en Groq-konto og API-nøkkel; ingen modellnedlasting eller lokal lagring er nødvendig. Kostnader kan påløpe.','Molnbearbetning skickar transkriptionstexten, men inte ljudet, till Groq. Ett Groq-konto och en API-nyckel krävs; ingen modellhämtning eller lokal lagring behövs. Kostnader kan tillkomma.','云处理会将转录文本（不含音频）发送给 Groq。需要 Groq 帐户和 API 密钥；无需下载模型或使用本地存储。可能产生费用。','클라우드 처리는 오디오를 제외한 전사 텍스트를 Groq에 보냅니다. Groq 계정과 API 키가 필요하며 모델 다운로드나 로컬 저장 공간은 필요하지 않습니다. 요금이 부과될 수 있습니다.','クラウド処理では、音声ではなく文字起こしテキストを Groq に送信します。Groq アカウントと API キーが必要ですが、モデルのダウンロードやローカルストレージは不要です。料金が発生する場合があります。'],
    'Formatting errors always fall back to the raw transcript so dictation is not lost.': ['In caso di errore viene sempre usata la trascrizione grezza, così la dettatura non va persa.','Si se produce un error, siempre se usa la transcripción sin procesar para no perder el dictado.','Em caso de erro, é sempre usada a transcrição sem processamento para que o ditado não se perca.','En cas d’erreur, la transcription brute est toujours utilisée afin de ne pas perdre la dictée.','Bei Fehlern wird immer das Rohtranskript verwendet, damit das Diktat nicht verloren geht.','Ved fejl bruges den rå transskription altid, så dikteringen ikke går tabt.','Ved feil brukes alltid den rå transkripsjonen, slik at dikteringen ikke går tapt.','Vid fel används alltid den råa transkriptionen så att dikteringen inte går förlorad.','如果格式化失败，将始终使用原始转录，以免丢失听写内容。','오류가 발생하면 받아쓰기 내용이 손실되지 않도록 항상 원본 전사로 돌아갑니다.','エラー時は必ず生の文字起こしに戻り、音声入力が失われないようにします。'],
    'When Groq is unavailable': ['Quando Groq non è disponibile','Cuando Groq no está disponible','Quando a Groq não está disponível','Lorsque Groq est indisponible','Wenn Groq nicht verfügbar ist','Når Groq ikke er tilgængelig','Når Groq ikke er tilgjengelig','När Groq inte är tillgängligt','Groq 不可用时','Groq을 사용할 수 없을 때','Groq が利用できない場合'],
    'Paste the raw transcript (no other provider)': ['Incolla la trascrizione grezza (nessun altro provider)','Pegar la transcripción sin procesar (sin otro proveedor)','Colar a transcrição sem processamento (sem outro fornecedor)','Coller la transcription brute (aucun autre fournisseur)','Rohtranskript einfügen (kein anderer Anbieter)','Indsæt den rå transskription (ingen anden udbyder)','Lim inn rå transkripsjon (ingen annen leverandør)','Klistra in den råa transkriptionen (ingen annan leverantör)','粘贴原始转录（不使用其他提供商）','원본 전사 붙여넣기(다른 공급자 사용 안 함)','生の文字起こしを貼り付ける（他のプロバイダーは使用しない）'],
    'Use Anthropic Claude Haiku if its API key is configured': ['Usa Anthropic Claude Haiku se la chiave API è configurata','Usar Anthropic Claude Haiku si su clave de API está configurada','Usar o Anthropic Claude Haiku se a chave de API estiver configurada','Utiliser Anthropic Claude Haiku si sa clé API est configurée','Anthropic Claude Haiku verwenden, wenn der API-Schlüssel konfiguriert ist','Brug Anthropic Claude Haiku, hvis API-nøglen er konfigureret','Bruk Anthropic Claude Haiku hvis API-nøkkelen er konfigurert','Använd Anthropic Claude Haiku om API-nyckeln är konfigurerad','如果已配置 API 密钥，则使用 Anthropic Claude Haiku','API 키가 설정되어 있으면 Anthropic Claude Haiku 사용','API キーが設定済みの場合は Anthropic Claude Haiku を使用'],
    'Llama 3.1 8B — Cloud, Groq (fastest)': ['Llama 3.1 8B — Cloud, Groq (più veloce)','Llama 3.1 8B — Nube, Groq (más rápido)','Llama 3.1 8B — Nuvem, Groq (mais rápido)','Llama 3.1 8B — Cloud, Groq (le plus rapide)','Llama 3.1 8B — Cloud, Groq (am schnellsten)','Llama 3.1 8B — Cloud, Groq (hurtigst)','Llama 3.1 8B — Sky, Groq (raskest)','Llama 3.1 8B — Moln, Groq (snabbast)','Llama 3.1 8B — 云端，Groq（最快）','Llama 3.1 8B — 클라우드, Groq(가장 빠름)','Llama 3.1 8B — クラウド、Groq（最速）'],
    'Llama 3.3 70B — Cloud, Groq (better quality)': ['Llama 3.3 70B — Cloud, Groq (qualità migliore)','Llama 3.3 70B — Nube, Groq (mejor calidad)','Llama 3.3 70B — Nuvem, Groq (melhor qualidade)','Llama 3.3 70B — Cloud, Groq (meilleure qualité)','Llama 3.3 70B — Cloud, Groq (bessere Qualität)','Llama 3.3 70B — Cloud, Groq (bedre kvalitet)','Llama 3.3 70B — Sky, Groq (bedre kvalitet)','Llama 3.3 70B — Moln, Groq (bättre kvalitet)','Llama 3.3 70B — 云端，Groq（质量更好）','Llama 3.3 70B — 클라우드, Groq(더 나은 품질)','Llama 3.3 70B — クラウド、Groq（高品質）'],
    'Llama 4 Scout 17B — Cloud, Groq': ['Llama 4 Scout 17B — Cloud, Groq','Llama 4 Scout 17B — Nube, Groq','Llama 4 Scout 17B — Nuvem, Groq','Llama 4 Scout 17B — Cloud, Groq','Llama 4 Scout 17B — Cloud, Groq','Llama 4 Scout 17B — Cloud, Groq','Llama 4 Scout 17B — Sky, Groq','Llama 4 Scout 17B — Moln, Groq','Llama 4 Scout 17B — 云端，Groq','Llama 4 Scout 17B — 클라우드, Groq','Llama 4 Scout 17B — クラウド、Groq'],
    'Qwen 3 32B — Cloud, Groq': ['Qwen 3 32B — Cloud, Groq','Qwen 3 32B — Nube, Groq','Qwen 3 32B — Nuvem, Groq','Qwen 3 32B — Cloud, Groq','Qwen 3 32B — Cloud, Groq','Qwen 3 32B — Cloud, Groq','Qwen 3 32B — Sky, Groq','Qwen 3 32B — Moln, Groq','Qwen 3 32B — 云端，Groq','Qwen 3 32B — 클라우드, Groq','Qwen 3 32B — クラウド、Groq'],
    'Application language': ['Lingua dell’applicazione','Idioma de la aplicación','Idioma da aplicação','Langue de l’application','Anwendungssprache','Applikationssprog','Programspråk','Programspråk','应用语言','앱 언어','アプリの言語'],
    'System default': ['Predefinita di sistema','Predeterminado del sistema','Predefinição do sistema','Par défaut du système','Systemstandard','Systemstandard','Systemstandard','Systemstandard','系统默认','시스템 기본값','システムのデフォルト'],
    'Changes apply immediately and are saved for the next launch.': ['Le modifiche vengono applicate subito e salvate per il prossimo avvio.','Los cambios se aplican inmediatamente y se guardan para el próximo inicio.','As alterações são aplicadas imediatamente e guardadas para o próximo arranque.','Les modifications s’appliquent immédiatement et sont enregistrées pour le prochain lancement.','Änderungen werden sofort angewendet und für den nächsten Start gespeichert.','Ændringer anvendes straks og gemmes til næste start.','Endringer tas i bruk umiddelbart og lagres til neste start.','Ändringar tillämpas direkt och sparas till nästa start.','更改会立即应用并保存供下次启动使用。','변경 사항은 즉시 적용되며 다음 실행을 위해 저장됩니다.','変更はすぐに適用され、次回起動時にも保持されます。'],
    'File':['File','Archivo','Ficheiro','Fichier','Datei','Filer','Fil','Arkiv','文件','파일','ファイル'], 'Edit':['Modifica','Editar','Editar','Modifier','Bearbeiten','Rediger','Rediger','Redigera','编辑','편집','編集'], 'View':['Vista','Ver','Ver','Affichage','Ansicht','Vis','Vis','Visa','查看','보기','表示'], 'Help':['Aiuto','Ayuda','Ajuda','Aide','Hilfe','Hjælp','Hjelp','Hjälp','帮助','도움말','ヘルプ'],
    'Library':['Libreria','Biblioteca','Biblioteca','Bibliothèque','Bibliothek','Bibliotek','Bibliotek','Bibliotek','资料库','라이브러리','ライブラリ'], 'Configuration':['Configurazione','Configuración','Configuração','Configuration','Konfiguration','Konfiguration','Konfigurasjon','Konfiguration','配置','설정','設定'],
    'Dashboard':['Dashboard','Panel','Painel','Tableau de bord','Übersicht','Oversigt','Oversikt','Översikt','仪表板','대시보드','ダッシュボード'], 'Recordings':['Registrazioni','Grabaciones','Gravações','Enregistrements','Aufnahmen','Optagelser','Opptak','Inspelningar','录音','녹음','録音'], 'Meetings':['Riunioni','Reuniones','Reuniões','Réunions','Besprechungen','Møder','Møter','Möten','会议','회의','会議'], 'Notes':['Note','Notas','Notas','Notes','Notizen','Noter','Notater','Anteckningar','笔记','노트','ノート'], 'Templates':['Modelli','Plantillas','Modelos','Modèles','Vorlagen','Skabeloner','Maler','Mallar','模板','템플릿','テンプレート'], 'Models':['Modelli','Modelos','Modelos','Modèles','Modelle','Modeller','Modeller','Modeller','模型','모델','モデル'], 'Engine':['Motore','Motor','Motor','Moteur','Engine','Motor','Motor','Motor','引擎','엔진','エンジン'], 'General':['Generale','General','Geral','Général','Allgemein','Generelt','Generelt','Allmänt','常规','일반','一般'],
    'Transcription':['Trascrizione','Transcripción','Transcrição','Transcription','Transkription','Transskription','Transkripsjon','Transkribering','转写','전사','文字起こし'],
    'Whisper models':['Modelli Whisper','Modelos de Whisper','Modelos Whisper','Modèles Whisper','Whisper-Modelle','Whisper-modeller','Whisper-modeller','Whisper-modeller','Whisper 模型','Whisper 모델','Whisperモデル'],
    'AI Notes':['Note IA','Notas de IA','Notas de IA','Notes IA','KI-Notizen','AI-noter','AI-notater','AI-anteckningar','AI 笔记','AI 노트','AIノート'],
    'Today':['Oggi','Hoy','Hoje','Aujourd’hui','Heute','I dag','I dag','I dag','今天','오늘','今日'], 'Start':['Avvia','Iniciar','Iniciar','Démarrer','Starten','Start','Start','Starta','开始','시작','開始'], 'Stop':['Interrompi','Detener','Parar','Arrêter','Stoppen','Stop','Stopp','Stoppa','停止','중지','停止'], 'Delete':['Elimina','Eliminar','Eliminar','Supprimer','Löschen','Slet','Slett','Ta bort','删除','삭제','削除'], 'Cancel':['Annulla','Cancelar','Cancelar','Annuler','Abbrechen','Annuller','Avbryt','Avbryt','取消','취소','キャンセル'], 'Save':['Salva','Guardar','Guardar','Enregistrer','Speichern','Gem','Lagre','Spara','保存','저장','保存'], 'Close':['Chiudi','Cerrar','Fechar','Fermer','Schließen','Luk','Lukk','Stäng','关闭','닫기','閉じる'], 'Add':['Aggiungi','Añadir','Adicionar','Ajouter','Hinzufügen','Tilføj','Legg til','Lägg till','添加','추가','追加'], 'Copy':['Copia','Copiar','Copiar','Copier','Kopieren','Kopiér','Kopier','Kopiera','复制','복사','コピー'],
    'Search recordings':['Cerca registrazioni','Buscar grabaciones','Pesquisar gravações','Rechercher des enregistrements','Aufnahmen suchen','Søg i optagelser','Søk i opptak','Sök inspelningar','搜索录音','녹음 검색','録音を検索'], 'Clear All':['Cancella tutto','Borrar todo','Limpar tudo','Tout effacer','Alle löschen','Ryd alle','Tøm alle','Rensa alla','全部清除','모두 지우기','すべて消去'], 'No recordings yet':['Nessuna registrazione','Aún no hay grabaciones','Ainda não há gravações','Aucun enregistrement','Noch keine Aufnahmen','Ingen optagelser endnu','Ingen opptak ennå','Inga inspelningar än','暂无录音','아직 녹음 없음','録音はまだありません'],
    'Appearance':['Aspetto','Apariencia','Aparência','Apparence','Darstellung','Udseende','Utseende','Utseende','外观','모양','外観'], 'System':['Sistema','Sistema','Sistema','Système','System','System','System','System','系统','시스템','システム'], 'Light':['Chiaro','Claro','Claro','Clair','Hell','Lys','Lys','Ljust','浅色','라이트','ライト'], 'Dark':['Scuro','Oscuro','Escuro','Sombre','Dunkel','Mørk','Mørk','Mörkt','深色','다크','ダーク'], 'Microphone':['Microfono','Micrófono','Microfone','Microphone','Mikrofon','Mikrofon','Mikrofon','Mikrofon','麦克风','마이크','マイク'], 'Language':['Lingua','Idioma','Idioma','Langue','Sprache','Sprog','Språk','Språk','语言','언어','言語'], 'Automatic updates':['Aggiornamenti automatici','Actualizaciones automáticas','Atualizações automáticas','Mises à jour automatiques','Automatische Updates','Automatiske opdateringer','Automatiske oppdateringer','Automatiska uppdateringar','自动更新','자동 업데이트','自動更新'], 'Permissions':['Autorizzazioni','Permisos','Permissões','Autorisations','Berechtigungen','Tilladelser','Tillatelser','Behörigheter','权限','권한','権限'], 'Support and local data':['Supporto e dati locali','Soporte y datos locales','Suporte e dados locais','Assistance et données locales','Support und lokale Daten','Support og lokale data','Støtte og lokale data','Support och lokala data','支持和本地数据','지원 및 로컬 데이터','サポートとローカルデータ'],
    'Update channel':['Canale di aggiornamento','Canal de actualizaciones','Canal de atualizações','Canal de mise à jour','Update-Kanal','Opdateringskanal','Oppdateringskanal','Uppdateringskanal','更新通道','업데이트 채널','更新チャンネル'],
    'Stable':['Stabile','Estable','Estável','Stable','Stabil','Stabil','Stabil','Stabil','稳定版','안정판','安定版'],
    'Nightly':['Nightly','Nightly','Nightly','Nightly','Nightly','Nightly','Nightly','Nightly','Nightly 版','Nightly','Nightly'],
    'Nightly receives prerelease builds for testing. They may be less reliable.':['Nightly riceve versioni preliminari da testare. Potrebbero essere meno affidabili.','Nightly recibe versiones preliminares para probar. Pueden ser menos fiables.','Nightly recebe versões de pré-lançamento para testes. Podem ser menos fiáveis.','Nightly reçoit des versions préliminaires à tester. Elles peuvent être moins fiables.','Nightly erhält Vorabversionen zum Testen. Sie können weniger zuverlässig sein.','Nightly modtager foreløbige builds til test. De kan være mindre pålidelige.','Nightly mottar forhåndsversjoner for testing. De kan være mindre pålitelige.','Nightly tar emot förhandsversioner för testning. De kan vara mindre tillförlitliga.','Nightly 会接收用于测试的预发布版本，可靠性可能较低。','Nightly는 테스트용 시험판 빌드를 받습니다. 안정성이 낮을 수 있습니다.','Nightly ではテスト用のプレリリース版を受け取ります。安定性が低い場合があります。'],
    'Check and download updates automatically':['Controlla e scarica automaticamente gli aggiornamenti','Buscar y descargar actualizaciones automáticamente','Procurar e transferir atualizações automaticamente','Rechercher et télécharger automatiquement les mises à jour','Updates automatisch suchen und herunterladen','Søg efter og download opdateringer automatisk','Se etter og last ned oppdateringer automatisk','Sök efter och hämta uppdateringar automatiskt','自动检查并下载更新','업데이트 자동 확인 및 다운로드','アップデートを自動的に確認してダウンロード'],
    'Switch to Stable? If your Nightly version is newer, the Stable version will replace it after the next update check.':['Passare a Stabile? Se la versione Nightly è più recente, la versione Stabile la sostituirà al prossimo controllo degli aggiornamenti.','¿Cambiar a Estable? Si tu versión Nightly es más reciente, la versión Estable la sustituirá tras la próxima búsqueda de actualizaciones.','Mudar para Estável? Se a versão Nightly for mais recente, a versão Estável irá substituí-la após a próxima verificação de atualizações.','Passer à Stable ? Si votre version Nightly est plus récente, la version Stable la remplacera après la prochaine recherche de mises à jour.','Zu Stabil wechseln? Falls Ihre Nightly-Version neuer ist, wird sie bei der nächsten Update-Suche durch die stabile Version ersetzt.','Skift til Stabil? Hvis din Nightly-version er nyere, erstatter den stabile version den efter næste opdateringstjek.','Bytte til Stabil? Hvis Nightly-versjonen er nyere, erstattes den av stabilversjonen etter neste oppdateringssjekk.','Byta till Stabil? Om Nightly-versionen är nyare ersätts den av den stabila versionen efter nästa uppdateringskontroll.','切换到稳定版？如果 Nightly 版本较新，下次检查更新后将由稳定版替换。','안정판으로 전환할까요? Nightly 버전이 더 최신이면 다음 업데이트 확인 후 안정판으로 교체됩니다.','安定版に切り替えますか？Nightly 版の方が新しい場合、次回のアップデート確認後に安定版へ置き換わります。'],
    'Finishing':['Completamento','Finalizando','A concluir','Finalisation','Abschluss','Afslutter','Fullfører','Slutför','正在完成','마무리 중','完了処理中'],
    'No microphone signal':['Nessun segnale dal microfono','No hay señal del micrófono','Sem sinal do microfone','Aucun signal du microphone','Kein Mikrofonsignal','Intet mikrofonsignal','Ingen mikrofonsignal','Ingen mikrofonsignal','没有麦克风信号','마이크 신호 없음','マイク信号がありません'],
    'Recording was too short':['Registrazione troppo breve','La grabación fue demasiado corta','A gravação foi demasiado curta','Enregistrement trop court','Aufnahme war zu kurz','Optagelsen var for kort','Opptaket var for kort','Inspelningen var för kort','录音时间太短','녹음이 너무 짧습니다','録音が短すぎます'],
    'Meeting recording':['Riunione in registrazione','Grabando reunión','Reunião a ser gravada','Enregistrement de la réunion','Meeting wird aufgenommen','Møde optages','Møtet tas opp','Mötet spelas in','正在录制会议','회의 녹음 중','会議を録音中'],
    'Recording':['Registrazione','Grabando','A gravar','Enregistrement','Aufnahme','Optager','Tar opp','Spelar in','正在录音','녹음 중','録音中'], 'Transcribing':['Trascrizione','Transcribiendo','A transcrever','Transcription','Transkription','Transskriberer','Transkriberer','Transkriberar','正在转写','변환 중','文字起こし中'], 'Mic unavailable':['Microfono non disponibile','Micrófono no disponible','Microfone indisponível','Microphone indisponible','Mikrofon nicht verfügbar','Mikrofon ikke tilgængelig','Mikrofon utilgjengelig','Mikrofonen är inte tillgänglig','麦克风不可用','마이크를 사용할 수 없음','マイクを使用できません'], 'Mic blocked':['Microfono bloccato','Micrófono bloqueado','Microfone bloqueado','Microphone bloqué','Mikrofon blockiert','Mikrofon blokeret','Mikrofon blokkert','Mikrofonen blockerad','麦克风已被阻止','마이크 차단됨','マイクがブロックされました'], 'Recording meeting · click to stop':['Registrazione riunione · fai clic per interrompere','Grabando reunión · haz clic para detener','A gravar reunião · clique para parar','Réunion en cours · cliquez pour arrêter','Besprechungsaufnahme · zum Stoppen klicken','Optager møde · klik for at stoppe','Tar opp møte · klikk for å stoppe','Spelar in möte · klicka för att stoppa','正在录制会议 · 点击停止','회의 녹음 중 · 중지하려면 클릭','会議を録音中 · クリックして停止'],
    'Could not add calendar feed: {0}':['Impossibile aggiungere il feed del calendario: {0}','No se pudo añadir el feed del calendario: {0}','Não foi possível adicionar o feed de calendário: {0}','Impossible d’ajouter le flux d’agenda : {0}','Kalender-Feed konnte nicht hinzugefügt werden: {0}','Kalenderfeedet kunne ikke tilføjes: {0}','Kalenderfeeden kunne ikke legges til: {0}','Kalenderflödet kunde inte läggas till: {0}','无法添加日历订阅源：{0}','캘린더 피드를 추가할 수 없습니다: {0}','カレンダーフィードを追加できませんでした: {0}'],
    'Calendar feed URL is invalid.':['L’URL del feed del calendario non è valido.','La URL del feed del calendario no es válida.','O URL do feed de calendário é inválido.','L’URL du flux d’agenda n’est pas valide.','Die Kalender-Feed-URL ist ungültig.','Kalenderfeedets URL er ugyldig.','Kalenderfeedens URL er ugyldig.','Kalenderflödets URL är ogiltig.','日历订阅源网址无效。','캘린더 피드 URL이 잘못되었습니다.','カレンダーフィードの URL が無効です。'],
    'Calendar feeds must use HTTPS.':['I feed del calendario devono usare HTTPS.','Los feeds del calendario deben usar HTTPS.','Os feeds de calendário têm de usar HTTPS.','Les flux d’agenda doivent utiliser HTTPS.','Kalender-Feeds müssen HTTPS verwenden.','Kalenderfeeds skal bruge HTTPS.','Kalenderfeeder må bruke HTTPS.','Kalenderflöden måste använda HTTPS.','日历订阅源必须使用 HTTPS。','캘린더 피드는 HTTPS를 사용해야 합니다.','カレンダーフィードは HTTPS を使用する必要があります。'],
    'Calendar feed URLs cannot contain embedded credentials.':['Gli URL dei feed del calendario non possono contenere credenziali incorporate.','Las URL de los feeds del calendario no pueden contener credenciales integradas.','Os URLs dos feeds de calendário não podem conter credenciais incorporadas.','Les URL des flux d’agenda ne peuvent pas contenir d’identifiants intégrés.','Kalender-Feed-URLs dürfen keine eingebetteten Anmeldedaten enthalten.','Kalenderfeed-URL’er må ikke indeholde indlejrede loginoplysninger.','Kalenderfeed-URL-er kan ikke inneholde innebygde påloggingsopplysninger.','Kalenderflödes-URL:er får inte innehålla inbäddade inloggningsuppgifter.','日历订阅源网址不能包含嵌入的凭据。','캘린더 피드 URL에는 자격 증명을 포함할 수 없습니다.','カレンダーフィードの URL に認証情報を含めることはできません。'],
    'This is Google Calendar’s browser page, not an ICS feed. In Google Calendar settings, copy the “Secret address in iCal format” instead.':['Questa è la pagina web di Google Calendar, non un feed ICS. Nelle impostazioni di Google Calendar copia invece l’“Indirizzo segreto in formato iCal”.','Esta es la página web de Google Calendar, no un feed ICS. En la configuración de Google Calendar, copia la “Dirección secreta en formato iCal”.','Esta é a página web do Google Calendar, não um feed ICS. Nas definições do Google Calendar, copie o “Endereço secreto em formato iCal”.','Ceci est la page web de Google Calendar, pas un flux ICS. Dans les paramètres de Google Calendar, copiez plutôt l’« Adresse secrète au format iCal ».','Dies ist die Webseite von Google Calendar, kein ICS-Feed. Kopieren Sie stattdessen in den Google Calendar-Einstellungen die „Privatadresse im iCal-Format“.','Dette er Google Calendars webside, ikke et ICS-feed. Kopiér i stedet den “Hemmelige adresse i iCal-format” i Google Calendars indstillinger.','Dette er Google Calendars nettside, ikke en ICS-feed. Kopier heller den “Hemmelige adressen i iCal-format” i innstillingene til Google Calendar.','Detta är Google Calendars webbsida, inte ett ICS-flöde. Kopiera i stället den “Hemliga adressen i iCal-format” i Google Calendars inställningar.','这是 Google Calendar 的网页，不是 ICS 订阅源。请改为在 Google Calendar 设置中复制“iCal 格式的私密地址”。','이것은 Google Calendar의 웹페이지이며 ICS 피드가 아닙니다. Google Calendar 설정에서 “iCal 형식의 비공개 주소”를 복사하세요.','これは Google Calendar のウェブページであり、ICS フィードではありません。Google Calendar の設定で「iCal形式の非公開URL」をコピーしてください。'],
    'This Google calendar is not public. Copy the “Secret address in iCal format” from its settings, or use the macOS Calendar integration if your organisation disables it.':['Questo calendario Google non è pubblico. Copia l’“Indirizzo segreto in formato iCal” dalle sue impostazioni oppure, se la tua organizzazione lo disabilita, usa l’integrazione macOS Calendar.','Este calendario de Google no es público. Copia la “Dirección secreta en formato iCal” desde su configuración o, si tu organización la desactiva, usa la integración macOS Calendar.','Este calendário Google não é público. Copie o “Endereço secreto em formato iCal” nas definições ou, se a sua organização o desativar, use a integração macOS Calendar.','Cet agenda Google n’est pas public. Copiez l’« Adresse secrète au format iCal » dans ses paramètres ou, si votre organisation la désactive, utilisez l’intégration macOS Calendar.','Dieser Google-Kalender ist nicht öffentlich. Kopieren Sie die „Privatadresse im iCal-Format“ aus den Einstellungen oder nutzen Sie die macOS-Calendar-Integration, falls Ihre Organisation sie deaktiviert.','Denne Google-kalender er ikke offentlig. Kopiér den “Hemmelige adresse i iCal-format” fra dens indstillinger, eller brug macOS Calendar-integrationen, hvis din organisation har slået den fra.','Denne Google-kalenderen er ikke offentlig. Kopier den “Hemmelige adressen i iCal-format” fra innstillingene, eller bruk macOS Calendar-integrasjonen hvis organisasjonen din har slått den av.','Den här Google-kalendern är inte offentlig. Kopiera den “Hemliga adressen i iCal-format” från dess inställningar, eller använd macOS Calendar-integrationen om din organisation har inaktiverat den.','此 Google 日历不是公开的。请在其设置中复制“iCal 格式的私密地址”；如果贵组织禁用了该地址，请改用 macOS Calendar 集成。','이 Google 캘린더는 공개 상태가 아닙니다. 설정에서 “iCal 형식의 비공개 주소”를 복사하거나, 조직에서 이를 비활성화한 경우 macOS Calendar 통합을 사용하세요.','この Google カレンダーは公開されていません。設定から「iCal形式の非公開URL」をコピーするか、組織で無効化されている場合は macOS Calendar 統合をご利用ください。'],
    'This Google calendar is not public. Copy the “Secret address in iCal format” from its settings.':['Questo calendario Google non è pubblico. Copia l’“Indirizzo segreto in formato iCal” dalle sue impostazioni.','Este calendario de Google no es público. Copia la “Dirección secreta en formato iCal” desde su configuración.','Este calendário Google não é público. Copie o “Endereço secreto em formato iCal” nas definições.','Cet agenda Google n’est pas public. Copiez l’« Adresse secrète au format iCal » dans ses paramètres.','Dieser Google-Kalender ist nicht öffentlich. Kopieren Sie die „Privatadresse im iCal-Format“ aus den Einstellungen.','Denne Google-kalender er ikke offentlig. Kopiér den “Hemmelige adresse i iCal-format” fra dens indstillinger.','Denne Google-kalenderen er ikke offentlig. Kopier den “Hemmelige adressen i iCal-format” fra innstillingene.','Den här Google-kalendern är inte offentlig. Kopiera den “Hemliga adressen i iCal-format” från dess inställningar.','此 Google 日历不是公开的。请在其设置中复制“iCal 格式的私密地址”。','이 Google 캘린더는 공개 상태가 아닙니다. 설정에서 “iCal 형식의 비공개 주소”를 복사하세요.','この Google カレンダーは公開されていません。設定から「iCal形式の非公開URL」をコピーしてください。'],
    'This feed requires sign-in. Use a private or secret ICS address instead.':['Questo feed richiede l’accesso. Usa invece un indirizzo ICS privato o segreto.','Este feed requiere iniciar sesión. Usa una dirección ICS privada o secreta.','Este feed requer início de sessão. Use um endereço ICS privado ou secreto.','Ce flux nécessite une connexion. Utilisez plutôt une adresse ICS privée ou secrète.','Dieser Feed erfordert eine Anmeldung. Verwenden Sie stattdessen eine private oder geheime ICS-Adresse.','Dette feed kræver login. Brug i stedet en privat eller hemmelig ICS-adresse.','Denne feeden krever pålogging. Bruk heller en privat eller hemmelig ICS-adresse.','Det här flödet kräver inloggning. Använd i stället en privat eller hemlig ICS-adress.','此订阅源需要登录。请改用私密或秘密的 ICS 地址。','이 피드는 로그인이 필요합니다. 비공개 또는 시크릿 ICS 주소를 사용하세요.','このフィードにはログインが必要です。非公開またはシークレットの ICS アドレスを使用してください。'],
    'The URL returned a web page, not calendar data. Check that the address is an ICS feed.':['L’URL ha restituito una pagina web, non dati di calendario. Verifica che l’indirizzo sia un feed ICS.','La URL devolvió una página web, no datos de calendario. Comprueba que la dirección sea un feed ICS.','O URL devolveu uma página web, não dados de calendário. Verifique se o endereço é um feed ICS.','L’URL a renvoyé une page web, pas des données d’agenda. Vérifiez que l’adresse est bien un flux ICS.','Die URL lieferte eine Webseite statt Kalenderdaten. Stellen Sie sicher, dass die Adresse ein ICS-Feed ist.','URL’en returnerede en webside, ikke kalenderdata. Sørg for, at adressen er et ICS-feed.','URL-en returnerte en nettside, ikke kalenderdata. Sørg for at adressen er en ICS-feed.','URL:en returnerade en webbsida, inte kalenderdata. Kontrollera att adressen är ett ICS-flöde.','该网址返回的是网页而非日历数据。请确认该地址是 ICS 订阅源。','URL이 캘린더 데이터가 아닌 웹페이지를 반환했습니다. 주소가 ICS 피드인지 확인하세요.','URL はカレンダーデータではなくウェブページを返しました。アドレスが ICS フィードであることを確認してください。']
  };
  const sourceMessages = window.__CRUNCHY_I18N_CATALOGS__?.en || {};
  const catalogs = {};
  for (const language of supported) catalogs[language] = Object.fromEntries(Object.keys(sourceMessages).map(key => [key, key]));
  Object.assign(catalogs.en, Object.fromEntries(Object.keys(phrases).map(key => [key, key])));
  supported.slice(1).forEach((language, index) => {
    Object.assign(catalogs[language], Object.fromEntries(Object.entries(phrases).map(([key, values]) => [key, values[index]])));
  });
  let locale = 'en';
  const reverseKeys = new Map();
  for (const catalog of Object.values(catalogs)) {
    for (const [key, value] of Object.entries(catalog)) if (!reverseKeys.has(value)) reverseKeys.set(value, key);
  }
  const parameterMatchers = Object.keys(catalogs.en).flatMap(key => {
    if (!/\{\d+\}/.test(key)) return [];
    const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/\\\{(\d+)\\\}/g, '(.+?)');
    return [{ key, expression: new RegExp(`^${escaped}$`, 's') }];
  });
  const sourceKey = value => {
    if (catalogs.en[value]) return value;
    return reverseKeys.get(value) || value;
  };
  const userContentSelector = '[data-i18n],input,textarea,[contenteditable],.cm-editor,.muya,#history,#foldersList,#notesList,#calendarList,#meetingsList,#meetingTranscript,#meetingAiNotes,#templatesList';
  const normalize = value => { const code = String(value || '').toLowerCase().split('-')[0]; return supported.includes(code) ? code : 'en'; };
  function t(key, vars = {}) { let value = catalogs[locale]?.[key] || catalogs.en[key] || key; for (const [name, replacement] of Object.entries(vars)) value = value.replaceAll(`{${name}}`, () => String(replacement)); return value; }
  function translateValue(visible) {
    const exact = sourceKey(visible);
    if (catalogs.en[exact]) return t(exact);
    for (const { key, expression } of parameterMatchers) {
      const match = visible.match(expression);
      if (match) return t(key, Object.fromEntries(match.slice(1).map((value, index) => [index, value])));
    }
    return visible;
  }
  function translate(root = document) {
    const i18nElements = root.matches?.('[data-i18n]') ? [root, ...root.querySelectorAll('[data-i18n]')] : root.querySelectorAll('[data-i18n]');
    i18nElements.forEach(el => { el.textContent = t(el.dataset.i18n); });
    const walker = document.createTreeWalker(root.body || root, NodeFilter.SHOW_TEXT, {
      acceptNode: node => node.parentElement?.closest(userContentSelector) ? NodeFilter.FILTER_REJECT : NodeFilter.FILTER_ACCEPT,
    });
    const nodes = []; while (walker.nextNode()) nodes.push(walker.currentNode);
    for (const node of nodes) { const visible = node.nodeValue.trim(); const translated = translateValue(visible); if (translated !== visible) node.nodeValue = node.nodeValue.replace(visible, translated); }
    const attributeElements = root.matches?.('[placeholder],[title],[aria-label]') ? [root, ...root.querySelectorAll('[placeholder],[title],[aria-label]')] : root.querySelectorAll('[placeholder],[title],[aria-label]');
    attributeElements.forEach(el => { for (const attr of ['placeholder','title','aria-label']) { const visible = el.getAttribute(attr); const key = sourceKey(visible); if (key && catalogs.en[key]) el.setAttribute(attr, t(key)); } });
    document.documentElement.lang = locale;
  }
  function setLocale(value, systemLocale = navigator.language) { locale = value === 'system' ? normalize(systemLocale) : normalize(value); translate(); window.dispatchEvent(new CustomEvent('localechange', { detail: locale })); }
  window.i18n = { t, translate, setLocale, get locale() { return locale; }, supported, catalogs };
  const nativeDialogs = { alert: window.alert?.bind(window), confirm: window.confirm?.bind(window), prompt: window.prompt?.bind(window) };
  for (const name of Object.keys(nativeDialogs)) if (nativeDialogs[name]) window[name] = (message, ...args) => nativeDialogs[name](translateValue(String(message)), ...args);
  let observing = false;
  new MutationObserver(records => {
    if (observing) return;
    observing = true;
    for (const record of records) for (const node of record.addedNodes) {
      if (node.nodeType === Node.TEXT_NODE && !node.parentElement?.closest(userContentSelector)) { const visible = node.nodeValue.trim(); node.nodeValue = node.nodeValue.replace(visible, translateValue(visible)); }
      else if (node.nodeType === Node.ELEMENT_NODE) translate(node);
    }
    observing = false;
  }).observe(document.documentElement, { childList: true, subtree: true });
})();
